LOAD_TRA ~%MOD_FOLDER%/Tra/%LANGUAGE%/Emily_bg2.tra~

LAF HANDLE_AUDIO
  STR_VAR
    audio_path = ~SkitiaNPCs/Audio/Emily~
    oggdec_path = ~SkitiaNPCs/Audio~
    sox_path = ~SkitiaNPCs/Audio/Emily~
END

//Allows Aasimar to be displayed on character screen.

OUTER_SET aas_lcase = RESOLVE_STR_REF(@520)
OUTER_SET aas_ucase = RESOLVE_STR_REF(@521)
APPEND ~racetext.2da~ ~AASIMAR   185        %aas_lcase%       -1         %aas_ucase%          -1~ UNLESS ~AASIMAR~



// Character SoA

COPY ~%MOD_FOLDER%/Cre/X3Emi.cre~ ~override/X3Emi.cre~
  SAY NAME1 @522
  SAY NAME2 @522
  WRITE_ASCII 0x248 ~X3Emi~ #8  //override script
  WRITE_ASCII 0x280 ~X3Emi~ #32  //DV
  WRITE_ASCII 0x2cc ~X3Emi~ #8   //pre-joining dialogue file
  WRITE_ASCII 0X34 ~X3EmiM~ #8   //small portrait
  WRITE_ASCII 0x3c ~X3EmiL~ #8   //medium portrait
  SAY BIO @523
  SAY MORALE @524
  SAY HAPPY @525
  SAY UNHAPPY_ANNOYED @526
  SAY UNHAPPY_SERIOUS @527
  SAY UNHAPPY_BREAKING_POINT ~~ // Emily only leaves if approval hits -99.
  SAY LEADER @529
  SAY TIRED @530
  SAY BORED @531
  SAY BATTLE_CRY1 @532
  SAY BATTLE_CRY2 @533
  SAY BATTLE_CRY3 @534
  SAY BATTLE_CRY4 @535
  SAY BATTLE_CRY5 @536
  SAY DAMAGE ~~ [Emildama]
  SAY DYING @538
  SAY HURT @539
  SAY AREA_FOREST @540
  SAY AREA_CITY @541
  SAY AREA_DUNGEON @542
  SAY AREA_DAY @543
  SAY AREA_NIGHT @544
  SAY SELECT_COMMON1 @545
  SAY SELECT_COMMON2 @546
  SAY SELECT_COMMON3 @547
  SAY SELECT_COMMON4 @548
  SAY SELECT_COMMON5 @549
  SAY SELECT_COMMON6 @550
  SAY SELECT_ACTION1 @551
  SAY SELECT_ACTION2 @552
  SAY SELECT_ACTION3 @553
  SAY SELECT_ACTION4 @554
  SAY SELECT_ACTION5 @555
  SAY SELECT_ACTION6 @556
  SAY SELECT_ACTION7 @557
  SAY CRITICAL_HIT @558
  SAY CRITICAL_MISS @559
  SAY TARGET_IMMUNE @560
  SAY INVENTORY_FULL @561 
  SAY SPELL_DISRUPTED @562
  SAY SET_A_TRAP ~~ []
  SAY HIDDEN_IN_SHADOWS @563
  SAY PICKED_POCKET ~~ []
  SAY SELECT_RARE1 @529
  SAY SELECT_RARE2 @529
  SAY REACT_TO_DIE_GENERAL @564
 
// Character ToB
 
  COPY ~%MOD_FOLDER%/Cre/X3Emi25.cre~ ~override/X3Emi25.cre~
  SAY NAME1 @522
  SAY NAME2 @522
  WRITE_ASCII 0x248 ~X3Emi25~ #8  //override script
  WRITE_ASCII 0x280 ~X3Emi~ #32  //DV
  WRITE_ASCII 0x2cc ~X3Emi25~ #8   //pre-joining dialogue file
  WRITE_ASCII 0X34 ~X3EmiM~ #8   //small portrait
  WRITE_ASCII 0x3c ~X3EmiL~ #8   //medium portrait
  SAY BIO @523
  SAY MORALE @524
  SAY HAPPY @525
  SAY UNHAPPY_ANNOYED @526
  SAY UNHAPPY_SERIOUS @527
  SAY UNHAPPY_BREAKING_POINT ~~ // Emily only leaves if approval hits -99.
  SAY LEADER @529
  SAY TIRED @530
  SAY BORED @531
  SAY BATTLE_CRY1 @532
  SAY BATTLE_CRY2 @533
  SAY BATTLE_CRY3 @534
  SAY BATTLE_CRY4 @535
  SAY BATTLE_CRY5 @536
  SAY DAMAGE ~~ [Emildama]
  SAY DYING @538
  SAY HURT @539
  SAY AREA_FOREST @540
  SAY AREA_CITY @541
  SAY AREA_DUNGEON @542
  SAY AREA_DAY @543
  SAY AREA_NIGHT @544
  SAY SELECT_COMMON1 @545
  SAY SELECT_COMMON2 @546
  SAY SELECT_COMMON3 @547
  SAY SELECT_COMMON4 @548
  SAY SELECT_COMMON5 @549
  SAY SELECT_COMMON6 @550
  SAY SELECT_ACTION1 @551
  SAY SELECT_ACTION2 @552
  SAY SELECT_ACTION3 @553
  SAY SELECT_ACTION4 @554
  SAY SELECT_ACTION5 @555
  SAY SELECT_ACTION6 @556
  SAY SELECT_ACTION7 @557
  SAY CRITICAL_HIT @558
  SAY CRITICAL_MISS @559
  SAY TARGET_IMMUNE @560
  SAY INVENTORY_FULL @561 
  SAY SPELL_DISRUPTED @562
  SAY SET_A_TRAP ~~ []
  SAY HIDDEN_IN_SHADOWS @563
  SAY PICKED_POCKET ~~ []
  SAY SELECT_RARE1 @529
  SAY SELECT_RARE2 @529
  SAY REACT_TO_DIE_GENERAL @564
  
APPEND ~pdialog.2da~
~X3Emi       X3EmiP             X3EmiJ			X3EmiD~
UNLESS ~X3Emi ~
UNLESS ~25POST~

APPEND ~pdialog.2da~
~X3Emi        X3EmiP             X3EmiJ            X3EmiD             X3Emi25P             X3Emi25J		X3Emi25D		X3Emi25~
UNLESS ~X3Emi~
IF ~25POST~

APPEND ~interdia.2da~
~X3Emi       BX3Emi~
UNLESS ~X3Emi~
UNLESS ~25FILE~

APPEND ~interdia.2da~
~X3Emi       BX3Emi       BX3Emi25~
UNLESS ~X3Emi~
IF ~25FILE~

//Epilogues
COPY ~%MOD_FOLDER%/Epilogue/X3EmiEp.2da~ ~override/X3EmiDN.2da~
REPLACE ~99999~ @51

COPY ~%MOD_FOLDER%/Epilogue/X3EmiEp.2da~ ~override/X3EmiDR.2da~
REPLACE ~99999~ @52

COPY ~%MOD_FOLDER%/Epilogue/X3EmiEp.2da~ ~override/X3EmiDA.2da~
REPLACE ~99999~ @53

COPY ~%MOD_FOLDER%/Epilogue/X3EmiEp.2da~ ~override/X3EmiHN.2da~
REPLACE ~99999~ @54

COPY ~%MOD_FOLDER%/Epilogue/X3EmiEp.2da~ ~override/X3EmiHR.2da~
REPLACE ~99999~ @55

COPY ~%MOD_FOLDER%/Epilogue/X3EmiEp.2da~ ~override/X3EmiHA.2da~
REPLACE ~99999~ @56


 // Journal Entries 
ADD_JOURNAL TITLE (@1) @2 @3 @4 @5 @6 @7 @8 @9 @10 @11 @12 @13 @14 @15 @16 @17 @18 @19 @20 @21 USING ~%MOD_FOLDER%/Tra/english/Emily_bg2.tra~ // To Be Heir
// Emily's Encounter with the Tethyrians in ToB has no quest associated with it.
  
  
  // Portraits 
    	COPY ~%MOD_FOLDER%/Portraits/X3EmiL.bmp~ ~override/X3EmiL.bmp~
		COPY ~%MOD_FOLDER%/Portraits/X3EmiM.bmp~ ~override/X3EmiM.bmp~
		
  // Items 
 COPY ~%MOD_FOLDER%/items/X3EBody.bam~ ~override/X3EBody.bam~ 
  COPY ~%MOD_FOLDER%/items/X3EBody.itm~ ~override/X3EBody.itm~ 
SAY NAME1 @522
SAY NAME2 @522
SAY DESC @565
  
  // Note, none of the arrows and bolts will be used by Emily at the moment. Can delete if we never use them.
   COPY_EXISTING ~%MOD_FOLDER%/Items/x3EArrow.bam~ ~override/x3EArrow.bam~
    COPY_EXISTING ~%MOD_FOLDER%/Items/x3EBolt.bam~ ~override/x3EBolt.bam~
 COPY_EXISTING ~%MOD_FOLDER%/Items/x3EArro1.itm~ ~override/x3EArro1.itm~
SAY NAME1 @566
SAY NAME2 @566
SAY DESC @567


 COPY_EXISTING ~%MOD_FOLDER%/Items/x3EArro2.itm~ ~override/x3EArro2.itm~
SAY NAME1 @568
SAY NAME2 @568
SAY DESC @569

 COPY_EXISTING ~%MOD_FOLDER%/Items/x3EArro3.itm~ ~override/x3EArro3.itm~
SAY NAME1 @570
SAY NAME2 @570
SAY DESC @571


 COPY_EXISTING ~%MOD_FOLDER%/Items/x3EArro4.itm~ ~override/x3EArro4.itm~
SAY NAME1 @572
SAY NAME2 @572
SAY DESC @573

COPY_EXISTING ~%MOD_FOLDER%/Items/x3EBolt1.itm~ ~override/x3EBolt1.itm~
SAY NAME1 @574
SAY NAME2 @574
SAY DESC @575


 COPY_EXISTING ~%MOD_FOLDER%/Items/x3EBolt2.itm~ ~override/x3EBolt2.itm~
SAY NAME1 @576
SAY NAME2 @576
SAY DESC @577


 COPY_EXISTING ~%MOD_FOLDER%/Items/x3EBolt3.itm~ ~override/x3EBolt3.itm~
SAY NAME1 @578
SAY NAME2 @578
SAY DESC @579


 COPY_EXISTING ~%MOD_FOLDER%/Items/x3EBolt4.itm~ ~override/x3EBolt4.itm~
SAY NAME1 @580
SAY NAME2 @580
SAY DESC @581

COPY_EXISTING ~%MOD_FOLDER%/Items/x3ESWORD.itm~ ~override/x3ESWORD.itm~
SAY NAME1 @582
SAY NAME2 @582
SAY DESC @583
COPY_EXISTING ~%MOD_FOLDER%/Items/x3RingE.itm~ ~override/x3RingE.itm~
SAY NAME1 @584
SAY NAME2 @584
SAY DESC @585 
    LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (@522)
	STR_VAR
	  resource = X3Emi
END
COPY ~%MOD_FOLDER%/Items/iX3EN.bam~ ~override/iX3EN.bam~ 
COPY ~%MOD_FOLDER%/Items/cX3EN.bam~ ~override/cX3EN.bam~ 
COPY ~%MOD_FOLDER%/Items/X3EN.itm~ ~override/X3EN.itm~ 
SAY NAME1 @586
SAY NAME2 @586
SAY DESC @587
OUTER_SET strref = RESOLVE_STR_REF (@588) 
APPEND item_use.2da ~X3EN Emily %strref% 3~
	 
COPY ~%MOD_FOLDER%/Items/X3EHEAD.itm~ ~override/X3EHEAD.itm~ 
SAY NAME1 @589
SAY NAME2 @589
SAY DESC  @590 
OUTER_SET strref = RESOLVE_STR_REF (@591) 
APPEND item_use.2da ~X3EHEAD Emily %strref% 3~
// Crafted Bows 
COPY ~%MOD_FOLDER%/Items/X3BOW09.itm~ ~override/X3BOW09.itm~ 
SAY NAME1 @592
SAY NAME2 @592
SAY DESC @593
COPY ~%MOD_FOLDER%/Items/X3BOW10.itm~ ~override/X3BOW10.itm~ 
SAY NAME1 @594
SAY NAME2 @594
SAY DESC @595

COPY ~%MOD_FOLDER%/Items/X3BOW10.itm~ ~override/X3BOW10.itm~ 
SAY NAME1 @596
SAY NAME2 @596
SAY DESC @597

COPY ~%MOD_FOLDER%/Items/X3BOW12.itm~ ~override/X3BOW12.itm~ 
SAY NAME1 @598
SAY NAME2 @598
SAY DESC @599
COPY ~%MOD_FOLDER%/Items/X3BOW13.itm~ ~override/X3BOW13.itm~ 
SAY NAME1 @600
SAY NAME2 @600
SAY DESC @601

COPY ~%MOD_FOLDER%/Items/X3BOW14.itm~ ~override/X3BOW14.itm~ 
SAY NAME1 @602
SAY NAME2 @602
SAY DESC @603
COPY ~%MOD_FOLDER%/Items/X3BOW15.itm~ ~override/X3BOW15.itm~ 
SAY NAME1 @604
SAY NAME2 @604
SAY DESC @605

COPY ~%MOD_FOLDER%/Items/X3XBow03.itm~ ~override/X3XBow03.itm~ 
SAY NAME1 @606
SAY NAME2 @606
SAY DESC @607

COPY ~%MOD_FOLDER%/Items/X3XBow06.itm~ ~override/X3XBow06.itm~ 
SAY NAME1 @608
SAY NAME2 @608
SAY DESC @609



COPY ~%MOD_FOLDER%/Items/X3XBow08.itm~ ~override/X3XBow08.itm~ 
SAY NAME1 @610
SAY NAME2 @610
SAY DESC @611

COPY ~%MOD_FOLDER%/Items/X3XBow10.itm~ ~override/X3XBow10.itm~ 
SAY NAME1 @612
SAY NAME2 @612
SAY DESC @613

COPY ~%MOD_FOLDER%/Items/X3XBow13.itm~ ~override/X3XBow13.itm~ 
SAY NAME1 @614
SAY NAME2 @614
SAY DESC @615

//Spell
COPY	"%MOD_FOLDER%/Spells/X3EFA.spl" override
	SAY NAME1 @616
	SAY NAME2 @616
	SAY 0x50 @617
	
	//Spell
COPY	"%MOD_FOLDER%/Spells/X3EFB.spl" override
	SAY NAME1 @618
	SAY NAME2 @618
	SAY 0x50 @619 

// Creatures 
COPY ~%MOD_FOLDER%/Cre/X3ECath.cre~ ~override/X3ECath.cre~
  WRITE_ASCII 0x248 ~X3ECATH~ #8  //override script
  WRITE_ASCII 0x280 ~X3ECATH~ #32  //DV
  WRITE_ASCII 0x2cc ~X3ECATH~ #8   // Dialogue 
  SAY NAME1 @620
  SAY NAME2 @620
COPY ~%MOD_FOLDER%/Cre/X3ECH.cre~ override 
  WRITE_ASCII 0x248 ~X3ECH~ #8  //override script
  WRITE_ASCII 0x280 ~X3ECH~ #32  //DV
  WRITE_ASCII 0x2cc ~X3ECH~ #8   // Dialogue 
  SAY NAME1 @621
  SAY NAME2 @621
COPY ~%MOD_FOLDER%/Cre/X3EGOD.cre~ override 
  WRITE_ASCII 0x248 ~X3EGOD~ #8  //override script
  WRITE_ASCII 0x280 ~X3EGOD~ #32  //DV
  WRITE_ASCII 0x2cc ~X3EGOD~ #8   // Dialogue 
  SAY NAME1 @622
  SAY NAME2 @622  
COPY ~%MOD_FOLDER%/Cre/X3EGVJ.cre~ override 
  WRITE_ASCII 0x248 ~X3EGVJ~ #8  //override script
  WRITE_ASCII 0x280 ~X3EGVJ~ #32  //DV
  WRITE_ASCII 0x2cc ~X3EGVJ~ #8   // Dialogue 
  SAY NAME1 @623
  SAY NAME2 @623  
COPY ~%MOD_FOLDER%/Cre/X3EGUARD.cre~ override 
  WRITE_ASCII 0x248 ~X3EGUARD~ #8  //override script
  WRITE_ASCII 0x280 ~X3EGUARD~ #32  //DV
  WRITE_ASCII 0x2cc ~X3EGUARD~ #8   // Dialogue 
  SAY NAME1 @624
  SAY NAME2 @624    
COPY ~%MOD_FOLDER%/Cre/X3EFATH.cre~ override 
  WRITE_ASCII 0x248 ~X3EFATH~ #8  //override script
  WRITE_ASCII 0x280 ~X3EFATH~ #32  //DV
  WRITE_ASCII 0x2cc ~X3EFATH~ #8   // Dialogue 
  SAY NAME1 @625
  SAY NAME2 @625 
COPY ~%MOD_FOLDER%/Cre/X3EBRO.cre~ override 
  WRITE_ASCII 0x248 ~X3EBRO~ #8  //override script
  WRITE_ASCII 0x280 ~X3EBRO~ #32  //DV
  WRITE_ASCII 0x2cc ~X3EBRO~ #8   // Dialogue 
  SAY NAME1 @626
  SAY NAME2 @626  
COPY ~%MOD_FOLDER%/Cre/X3EDAR.cre~ override 
  WRITE_ASCII 0x248 ~X3EDAR~ #8  //override script
  WRITE_ASCII 0x280 ~X3EDAR~ #32  //DV
  WRITE_ASCII 0x2cc ~X3EDAR~ #8   // Dialogue 
  SAY NAME1 @627
  SAY NAME2 @627    
COPY ~%MOD_FOLDER%/Cre/X3EPHL.cre~ override 
  WRITE_ASCII 0x248 ~X3EPHL~ #8  //override script
  WRITE_ASCII 0x280 ~X3EPHL~ #32  //DV
  WRITE_ASCII 0x2cc ~X3EPHL~ #8   // Dialogue 
  SAY NAME1 @628
  SAY NAME2 @628    
COPY ~%MOD_FOLDER%/Cre/X3EMYR.cre~ override 
  WRITE_ASCII 0x248 ~X3EMYR~ #8  //override script
  WRITE_ASCII 0x280 ~X3EMYR~ #32  //DV
  WRITE_ASCII 0x2cc ~X3EMYR~ #8   // Dialogue 
  SAY NAME1 @629
  SAY NAME2 @629     
COPY ~%MOD_FOLDER%/Cre/X3EDER.cre~ override 
  WRITE_ASCII 0x248 ~X3EDER~ #8  //override script
  WRITE_ASCII 0x280 ~X3EDER~ #32  //DV
  WRITE_ASCII 0x2cc ~X3EDER~ #8   // Dialogue 
  SAY NAME1 @630
  SAY NAME2 @630  
COPY ~%MOD_FOLDER%/Cre/X3EMES.cre~ override 
  WRITE_ASCII 0x248 ~X3EMES~ #8  //override script
  WRITE_ASCII 0x280 ~X3EMES~ #32  //DV
  WRITE_ASCII 0x2cc ~X3EMES~ #8   // Dialogue 
  SAY NAME1 @631
  SAY NAME2 @631   
COPY ~%MOD_FOLDER%/Cre/X3ELOVE.cre~ ~override/X3Elove.cre~
  WRITE_ASCII 0x248 ~X3Elove~ #8  //override script
  WRITE_ASCII 0x280 ~X3Elove~ #32  //DV
  WRITE_ASCII 0x2cc ~X3Elove~ #8   // Dialogue 
  SAY NAME1 @632
  SAY NAME2 @632    
// Creature and Cutscene Scripts 
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Scripts/X3ECath.baf~ 
~%MOD_FOLDER%/Scripts/X3Emi.baf~ 
~%MOD_FOLDER%/Scripts/X3EmiD.baf~ 
~%MOD_FOLDER%/Scripts/X3Emi25.baf~
~%MOD_FOLDER%/Scripts/X3Emi25D.baf~
~%MOD_FOLDER%/Scripts/X3EBRO.baf~  
~%MOD_FOLDER%/Scripts/X3EMES.baf~ 
~%MOD_FOLDER%/Scripts/X3EDAR.baf~   
~%MOD_FOLDER%/Scripts/X3ECH.baf~  
~%MOD_FOLDER%/Scripts/X3EGVJ.baf~  
~%MOD_FOLDER%/Scripts/X3ECH.baf~  
~%MOD_FOLDER%/Scripts/X3EGUARD.baf~  
~%MOD_FOLDER%/Scripts/X3EFATH.baf~  
 ~%MOD_FOLDER%/Scripts/X3ECut01.baf~ 
~%MOD_FOLDER%/Scripts/X3ECut02.baf~ 
~%MOD_FOLDER%/Scripts/X3ECut03.baf~ 
~%MOD_FOLDER%/Scripts/X3ECut04.baf~ 
~%MOD_FOLDER%/Scripts/X3ECut05.baf~ 
~%MOD_FOLDER%/Scripts/X3EBodhi.baf~ 
~%MOD_FOLDER%/Scripts/X3EW1.baf~ 
// Area Scripts 

  EXTEND_TOP ~ar0704.bcs~ ~%MOD_FOLDER%/Scripts/ar0704.baf~
  EXTEND_BOTTOM ~ar0515.bcs~ ~%MOD_FOLDER%/Scripts/ar0515.baf~  
ACTION_IF GAME_IS ~eet~ BEGIN
  EXTEND_BOTTOM ~ar1006.bcs~ ~%MOD_FOLDER%/Scripts/EET/ar1006.baf~ 
  EXTEND_BOTTOM ~ar1000.bcs~ ~%MOD_FOLDER%/Scripts/EET/ar1000.baf~ 
  EXTEND_BOTTOM ~ar0903.bcs~ ~%MOD_FOLDER%/Scripts/EET/ar0903.baf~  
END ELSE BEGIN
  EXTEND_BOTTOM ~ar1006.bcs~ ~%MOD_FOLDER%/Scripts/ar1006.baf~ 
  EXTEND_BOTTOM ~ar1000.bcs~ ~%MOD_FOLDER%/Scripts/ar1000.baf~ 
  EXTEND_BOTTOM ~ar0903.bcs~ ~%MOD_FOLDER%/Scripts/ar0903.baf~  
END  

//Dialogue 
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3Emi.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3Emi.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3Emi25.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3Emi25.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3ECH.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3ECH.tra~ // Contains X3ECH and X3EIS creature file dialogues.
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3EGVJ.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3EGVJ.tra~ // Contains X3EGVJ and X3EGUARD creature file dialogues.
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3EMYR.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3EMYR.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3EBRO.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3EBRO.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3EMES.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3EMES.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3EFATH.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3EFATH.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/BX3Emi.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/BX3Emi.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3EmiJ.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3EmiJ.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/BX3Emi25.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/BX3Emi25.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3Emi25J.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3Emi25J.tra~

LOAD_TRA ~%MOD_FOLDER%/Tra/%LANGUAGE%/setup.tra~