LOAD_TRA ~%MOD_FOLDER%/Tra/%LANGUAGE%/Helga_bg2.tra~
LAF HANDLE_AUDIO
  STR_VAR
    audio_path = ~SkitiaNPCs/Audio/Helga~
    oggdec_path = ~SkitiaNPCs/Audio~
    sox_path = ~SkitiaNPCs/Audio/Helga~
END


ADD_KIT ~X3cleric~
	~X3cleric 1 1 1 1 1 1 1 1~
 // appended column-wise to WEAPPROF.2da
//11                                T   S           F   Q             S S
//10                                W   C           L   U             W I
//9                         B L S   O   I   W       A   A             O N
//8                         A O H   H   M   A       I   R C   S       R G
//7         L S           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6         _ _       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5         S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4         W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3         O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2         R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1         D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
 ~X3cleric	0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

 	~X3cleric 8 3 12 9 9 7~
	~X3cleric 0 0 0 0 0 0~
	~X3cleric 0 0 0 0 0 0~
    ~X3cleric 0 0 0 0 17 0~
	~X3cleric 0 0 0 1 0 0 1 1 0~
	~X3cleric 0 0 0 0 0 0~
	~%MOD_FOLDER%/2da/X3helcl.2da~
	~~ /*Set this to ~K_C_D~ and not ~~ if you want to play it.*/
	~0x00080000 3~
	~CL0~
	~* * * * * * * * * * * * * * * * * * *  *~
	SAY @633
	SAY @633
	SAY @634 

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~X3cleric~
		clswpbon = ~1 0 3~
		numwslot = ~2~
		hpclass = ~HPPRS~
		clsrcreq = ~0 0 0 1 0 0 0~
		clasthac = ~0~
END

COPY	"%MOD_FOLDER%/Spells/X3HBolt.spl" override
SAY NAME1 @635
SAY NAME2 @635
SAY 0x50  @636
COPY	"%MOD_FOLDER%/Spells/X3HurlS.spl" override
	SAY NAME1 @637
	SAY NAME2 @637
	SAY 0x50 @638 
COPY	"%MOD_FOLDER%/Items/x3HSW.bam" override

// Store 
COPY ~%MOD_FOLDER%/Items/X3HGEM.STO~ override

COPY_EXISTING ~%MOD_FOLDER%/Items/x3ERing.itm~ ~override/x3ERing.itm~
SAY NAME1 @639
SAY NAME2 @639
SAY DESC @640 
  
// Character SoA

COPY ~%MOD_FOLDER%/Cre/X3Hel.cre~ ~override/X3Hel.cre~
  SAY NAME1 @641
  SAY NAME2 @641
  WRITE_ASCII 0x248 ~X3Hel~ #8  //override script
  WRITE_ASCII 0x280 ~X3Hel~ #32  //DV
  WRITE_ASCII 0x2cc ~X3Hel~ #8   //pre-joining dialogue file
  WRITE_ASCII 0X34 ~X3HelM~ #8   //small portrait
  WRITE_ASCII 0x3c ~X3HelL~ #8   //medium portrait
  SAY BIO @642
  SAY MORALE @643 //
  SAY HAPPY @644 //
  SAY UNHAPPY_ANNOYED @645
  SAY UNHAPPY_SERIOUS @646
  SAY UNHAPPY_BREAKING_POINT @647
  SAY LEADER @648  //
  SAY TIRED @649  //
  SAY BORED @650 //
  SAY BATTLE_CRY1 @651 //
  SAY BATTLE_CRY2 ~~ [X3HeCry2]
  SAY BATTLE_CRY3 @653 //
  SAY BATTLE_CRY4 @654 //
  SAY BATTLE_CRY5 @655 //
  SAY DAMAGE ~~ [X3HeDam] //
  SAY DYING ~~ [X3HeDead] //
  SAY HURT @658 //
  SAY AREA_FOREST @659 
  SAY AREA_CITY @660
  SAY AREA_DUNGEON @661
  SAY AREA_DAY ~Isn't it Grand?~[X3HeGran]
  SAY AREA_NIGHT @663
  SAY SELECT_COMMON1 @664 //
  SAY SELECT_COMMON2 @665 //
  SAY SELECT_COMMON3 @666
  SAY SELECT_COMMON4 @667
  SAY SELECT_COMMON5 @668
  SAY SELECT_COMMON6 @666
  SAY SELECT_ACTION1 @669
  SAY SELECT_ACTION2 @670
  SAY SELECT_ACTION3 @671
  SAY SELECT_ACTION4 @672
  SAY SELECT_ACTION5 @673
  SAY SELECT_ACTION6 @674
  SAY SELECT_ACTION7 @675
  SAY CRITICAL_HIT ~~[X3HeCrit] //
  SAY CRITICAL_MISS @677 //
  SAY TARGET_IMMUNE @678 // 
  SAY INVENTORY_FULL @679 //
  SAY SPELL_DISRUPTED @680 // 
  SAY SET_A_TRAP ~~ []
  SAY HIDDEN_IN_SHADOWS ~~ []
  SAY PICKED_POCKET ~~ []	  
  SAY SELECT_RARE1 @669
  SAY SELECT_RARE2 @669  
  WRITE_SHORT 0x246 (IDS_OF_SYMBOL (~kit~ ~X3cleric~))
  
 // Character ToB 
 
 COPY ~%MOD_FOLDER%/Cre/X3Hel25.cre~ ~override/X3Hel25.cre~
  SAY NAME1 @641
  SAY NAME2 @641
  WRITE_ASCII 0x248 ~X3Hel25~ #8  //override script
  WRITE_ASCII 0x280 ~X3Hel~ #32  //DV
  WRITE_ASCII 0x2cc ~X3Hel25~ #8   //pre-joining dialogue file
  WRITE_ASCII 0X34 ~X3HelM~ #8   //small portrait
  WRITE_ASCII 0x3c ~X3HelL~ #8   //medium portrait
  SAY BIO @642
  SAY MORALE @643 //
  SAY HAPPY @644 //
  SAY UNHAPPY_ANNOYED @645
  SAY UNHAPPY_SERIOUS @646
  SAY UNHAPPY_BREAKING_POINT @647
  SAY LEADER @648  //
  SAY TIRED @649  //
  SAY BORED @650 //
  SAY BATTLE_CRY1 @651 //
  SAY BATTLE_CRY2 ~~ [X3HeCry2]
  SAY BATTLE_CRY3 @653 //
  SAY BATTLE_CRY4 @654 //
  SAY BATTLE_CRY5 @655 //
  SAY DAMAGE ~~ [X3HeDam] //
  SAY DYING ~~ [X3HeDead] //
  SAY HURT @658 //
  SAY AREA_FOREST @659 
  SAY AREA_CITY @660
  SAY AREA_DUNGEON @661
  SAY AREA_DAY ~Isn't it Grand?~[X3HeGran]
  SAY AREA_NIGHT @663
  SAY SELECT_COMMON1 @664 //
  SAY SELECT_COMMON2 @665 //
  SAY SELECT_COMMON3 @666
  SAY SELECT_COMMON4 @667
  SAY SELECT_COMMON5 @668
  SAY SELECT_COMMON6 @666
  SAY SELECT_ACTION1 @669
  SAY SELECT_ACTION2 @670
  SAY SELECT_ACTION3 @671
  SAY SELECT_ACTION4 @672
  SAY SELECT_ACTION5 @673
  SAY SELECT_ACTION6 @674
  SAY SELECT_ACTION7 @675
  SAY CRITICAL_HIT ~~[X3HeCrit] //
  SAY CRITICAL_MISS @677 //
  SAY TARGET_IMMUNE @678 // 
  SAY INVENTORY_FULL @679 //
  SAY SPELL_DISRUPTED @680 // 
  SAY SET_A_TRAP ~~ []
  SAY HIDDEN_IN_SHADOWS ~~ []
  SAY PICKED_POCKET ~~ []	  
  SAY SELECT_RARE1 @669
  SAY SELECT_RARE2 @669
  WRITE_SHORT 0x246 (IDS_OF_SYMBOL (~kit~ ~X3cleric~))
  
  APPEND ~pdialog.2da~
~X3Hel       X3HelP             X3HelJ			X3HelD~
UNLESS ~X3Hel ~
UNLESS ~25POST~

APPEND ~pdialog.2da~
~X3Hel        X3HelP             X3HelJ            X3HelD             X3Hel25P             X3Hel25J		X3Hel25D		X3Hel25~
UNLESS ~X3Hel~
IF ~25POST~

APPEND ~interdia.2da~
~X3Hel       BX3Hel~
UNLESS ~X3Hel~
UNLESS ~25FILE~

APPEND ~interdia.2da~
~X3Hel       BX3Hel       BX3Hel25~
UNLESS ~X3Hel~
IF ~25FILE~
 //Epilogues
COPY ~%MOD_FOLDER%/Epilogue/X3HelEp.2da~ ~override/X3Hel01.2da~
REPLACE ~99999~ @51

COPY ~%MOD_FOLDER%/Epilogue/X3HelEp.2da~ ~override/X3Hel02.2da~
REPLACE ~99999~ @52 
 // Journal Entries 
ADD_JOURNAL TITLE (@1) @2 @3 @4 @5 @6 @7 @8 @9 @10 USING ~%MOD_FOLDER%/Tra/english/Helga_bg2.tra~ // Rulendo's Gauntlet 
ADD_JOURNAL TITLE (@11) @12 @13 @14 @15 @16 @17 @18 @19 @20 @21 @22 USING ~%MOD_FOLDER%/Tra/english/Helga_bg2.tra~ // Helga's Son  
  
  // Portraits 
  		COPY ~%MOD_FOLDER%/Portraits/X3HelL.bmp~ ~override/X3HelL.bmp~
		COPY ~%MOD_FOLDER%/Portraits/X3HelM.bmp~ ~override/X3HelM.bmp~
// ITEMS
COPY	"%MOD_FOLDER%/Items/x3HBlade.itm" override
SAY NAME1 @635
SAY NAME2 @635
SAY DESC  @682

COPY	"%MOD_FOLDER%/Items/x3HBlad2.itm" override
SAY NAME1 @635
SAY NAME2 @635
SAY DESC  @683

COPY	"%MOD_FOLDER%/Items/x3HBlad3.itm" override
SAY NAME1 @635
SAY NAME2 @635
SAY DESC  @684

COPY	"%MOD_FOLDER%/Items/x3HBlad4.itm" override
SAY NAME1 @635
SAY NAME2 @635
SAY DESC  @685

COPY	"%MOD_FOLDER%/Items/x3HBlad5.itm" override
SAY NAME1 @635
SAY NAME2 @635
SAY DESC  @686

COPY_EXISTING ~%MOD_FOLDER%/Items/X3HPC.itm~ ~override/X3HPC.itm~
SAY NAME1 @687
SAY NAME2 @687
SAY DESC @688
COPY_EXISTING ~%MOD_FOLDER%/Items/X3HPW.itm~ ~override/X3HPW.itm~
SAY NAME1 @689
SAY NAME2 @689
SAY DESC @690		
COPY_EXISTING ~%MOD_FOLDER%/Items/X3HGEM.itm~ ~override/X3HGEM.itm~
SAY NAME1 @691
SAY NAME2 @691
SAY DESC @692	

		// Creatures 
COPY ~%MOD_FOLDER%/Cre/X3HARV.cre~ ~override/X3HARV.cre~
  WRITE_ASCII 0x248 ~X3HARV~ #8  //override script
  WRITE_ASCII 0x280 ~X3HARV~ #32  //DV
  WRITE_ASCII 0x2cc ~X3HARV~ #8   // Dialogue 
  SAY NAME1 @693
  SAY NAME2 @693
COPY ~%MOD_FOLDER%/Cre/X3HPOOR.cre~ ~override/X3HPOOR.cre~
  WRITE_ASCII 0x248 ~X3HPOOR~ #8  //override script
  WRITE_ASCII 0x280 ~X3HPOOR~ #32  //DV
  WRITE_ASCII 0x2cc ~X3HPOOR~ #8   // Dialogue 
  SAY NAME1 @694
  SAY NAME2 @694  
COPY ~%MOD_FOLDER%/Cre/X3HRL.cre~ ~override/X3HRL.cre~
  WRITE_ASCII 0x248 ~X3HRL~ #8  //override script
  WRITE_ASCII 0x280 ~X3HRL~ #32  //DV
  WRITE_ASCII 0x2cc ~X3HRL~ #8   // Dialogue 
  SAY NAME1 @695
  SAY NAME2 @695 
COPY ~%MOD_FOLDER%/Cre/X3HR1F1.cre~ ~override/X3HR1F1.cre~
  WRITE_ASCII 0x280 ~X3HR1F1~ #32  //DV
  WRITE_ASCII 0x248 ~X3HR1F1~ #8  //override script
  WRITE_ASCII 0x2cc ~X3HR1F1~ #8   // Dialogue   
  SAY NAME1 @696
  SAY NAME2 @696  
COPY ~%MOD_FOLDER%/Cre/X3HR1F2.cre~ ~override/X3HR1F2.cre~
  WRITE_ASCII 0x280 ~X3HR1F2~ #32  //DV
  WRITE_ASCII 0x248 ~X3HR1F2~ #8  //override script  
  SAY NAME1 @696
  SAY NAME2 @696   
COPY ~%MOD_FOLDER%/Cre/X3HR1R.cre~ ~override/X3HR1R.cre~
  WRITE_ASCII 0x280 ~X3HR1R~ #32  //DV
  WRITE_ASCII 0x248 ~X3HR1R~ #8  //override script  
  SAY NAME1 @697
  SAY NAME2 @697    
COPY ~%MOD_FOLDER%/Cre/X3HR2M1.cre~ ~override/X3HR2M1.cre~
  WRITE_ASCII 0x280 ~X3HR2M1~ #32  //DV
  WRITE_ASCII 0x248 ~X3HR2M1~ #8  //override script
  WRITE_ASCII 0x2cc ~X3HR2M1~ #8   // Dialogue   
  SAY NAME1 @698
  SAY NAME2 @698  
COPY ~%MOD_FOLDER%/Cre/X3HR2F1.cre~ ~override/X3HR2F1.cre~
  WRITE_ASCII 0x280 ~X3HR2F1~ #32  //DV
  WRITE_ASCII 0x248 ~X3HR2F1~ #8  //override script  
  SAY NAME1 @696
  SAY NAME2 @696   
COPY ~%MOD_FOLDER%/Cre/X3HR2C1.cre~ ~override/X3HR2C1.cre~
  WRITE_ASCII 0x280 ~X3HR2C1~ #32  //DV
  WRITE_ASCII 0x248 ~X3HR2C1~ #8  //override script  
  SAY NAME1 @699
  SAY NAME2 @699  
COPY ~%MOD_FOLDER%/Cre/X3HDD.cre~ ~override/X3HDD.cre~
  WRITE_ASCII 0x280 ~X3HDD~ #32  //DV
  WRITE_ASCII 0x248 ~X3HDD~ #8  //override script
  WRITE_ASCII 0x2cc ~X3HDD~ #8   // Dialogue   
  SAY NAME1 @700
  SAY NAME2 @700  
COPY ~%MOD_FOLDER%/Cre/X3HDC.cre~ ~override/X3HDC.cre~
  WRITE_ASCII 0x280 ~X3HDC~ #32  //DV
  WRITE_ASCII 0x248 ~X3HDC~ #8  //override script  
  SAY NAME1 @701
  SAY NAME2 @701   
COPY ~%MOD_FOLDER%/Cre/X3HDB.cre~ ~override/X3HDB.cre~
  WRITE_ASCII 0x280 ~X3HDB~ #32  //DV
  WRITE_ASCII 0x248 ~X3HDB~ #8  //override script  
  SAY NAME1 @702
  SAY NAME2 @702   
COPY ~%MOD_FOLDER%/Cre/X3HSON.cre~ ~override/X3HSON.cre~
  WRITE_ASCII 0x280 ~X3HSON~ #32  //DV
  WRITE_ASCII 0x248 ~X3HSON~ #8  //override script
  WRITE_ASCII 0x2cc ~X3HSON~ #8   // Dialogue   
  SAY NAME1 @703
  SAY NAME2 @703   
COPY ~%MOD_FOLDER%/Cre/X3HGEM.cre~ ~override/X3HGEM.cre~
  WRITE_ASCII 0x280 ~X3HGEM~ #32  //DV
  WRITE_ASCII 0x248 ~X3HGEM~ #8  //override script
  WRITE_ASCII 0x2cc ~X3HGEM~ #8   // Dialogue   
  SAY NAME1 @704
  SAY NAME2 @704 
COPY ~%MOD_FOLDER%/Cre/X3HSCRY.cre~ ~override/X3HSCRY.cre~
  WRITE_ASCII 0x280 ~X3HSCRY~ #32  //DV
  WRITE_ASCII 0x248 ~X3HSCRY~ #8  //override script
  WRITE_ASCII 0x2cc ~X3HSCRY~ #8   // Dialogue   
  SAY NAME1 @705
  SAY NAME2 @705    
// Creature Scripts 
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Scripts/X3Hel.baf~ 
~%MOD_FOLDER%/Scripts/X3HelD.baf~ 
~%MOD_FOLDER%/Scripts/X3Hel25.baf~ 
~%MOD_FOLDER%/Scripts/X3HPOOR.baf~ 
~%MOD_FOLDER%/Scripts/X3HPit.baf~ 
~%MOD_FOLDER%/Scripts/X3HDD.baf~ 
~%MOD_FOLDER%/Scripts/X3HRL.baf~
~%MOD_FOLDER%/Scripts/X3HSON.baf~
// Area Scripts 
/*Helga does use AR0400, if there is a change in Kale's script that changes his spawn point, uncomment the below */
//EXTEND_TOP ~ar0400.bcs~ ~%MOD_FOLDER%/Scripts/ar0400.baf~
  EXTEND_TOP ~ar0709.bcs~ ~%MOD_FOLDER%/Scripts/ar0709.baf~
    EXTEND_TOP ~ar0406.bcs~ ~%MOD_FOLDER%/Scripts/ar0406.baf~
    EXTEND_BOTTOM ~ar5000.bcs~ ~%MOD_FOLDER%/Scripts/ar5000.baf~	
	    EXTEND_TOP ~ar5500.bcs~ ~%MOD_FOLDER%/Scripts/ar5500.baf~
	// Helga uses AR5501, but Vienxay already grabs this file. Uncomment if that changes.
//		    EXTEND_BOTTOM ~ar5501.bcs~ ~%MOD_FOLDER%/Scripts/ar5501.baf~
 // Cutscenes 
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Scripts/X3HCut01.baf~  
~%MOD_FOLDER%/Scripts/X3HCut02.baf~  
~%MOD_FOLDER%/Scripts/X3HCut03.baf~ 
~%MOD_FOLDER%/Scripts/X3HCut04.baf~ 
~%MOD_FOLDER%/Scripts/X3HCut05.baf~ //Cutscene if Scrier does the spell
  //Dialogue 
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3Hel.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3Hel.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3Hel25.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3Hel25.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3HRL.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3HRL.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3HDD.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3HDD.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3HSON.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3HSON.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3HGEM.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3HGEM.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3HSCRY.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3HSCRY.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/BX3Hel.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/BX3Hel.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3HelJ.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3HelJ.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/BX3Hel25.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/BX3Hel25.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3Hel25J.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3Hel25J.tra~

PRINT ~Choose a portrait for Helga (check mod folder for portraits):~

PRINT ~Please choose one of the following:
[1] Default by Acifer
[2] Alt NWN Portrait~

OUTER_SPRINT ~portrait~ ~placeholder_value~
OUTER_WHILE (!(IS_AN_INT ~portrait~) OR (~portrait~ > 0x2) OR (~portrait~ < 0x1)) BEGIN
  ACTION_READLN ~portrait~
END
      ACTION_IF ("portrait" = 1) THEN BEGIN
		COPY ~%MOD_FOLDER%/Portraits/HelgaL.bmp~ ~override/X3HelL.bmp~
		COPY ~%MOD_FOLDER%/Portraits/HelgaM.bmp~ ~override/X3HelM.bmp~
      PRINT ~Portrait: Default by Acifer~
	  END
      ACTION_IF ("portrait" = 2) THEN BEGIN
		COPY ~%MOD_FOLDER%/Portraits/X3HelL.bmp~ ~override/X3HelL.bmp~
		COPY ~%MOD_FOLDER%/Portraits/X3HelM.bmp~ ~override/X3HelM.bmp~
      PRINT ~Portrait: Alt NWN Portrait~
	  END
	  
LOAD_TRA ~%MOD_FOLDER%/Tra/%LANGUAGE%/setup.tra~