LOAD_TRA ~%MOD_FOLDER%/Tra/%LANGUAGE%/KALE_bg2.tra~
LAF HANDLE_AUDIO
  STR_VAR
    audio_path = ~SkitiaNPCs/Audio/Kale~
    oggdec_path = ~SkitiaNPCs/Audio~
    sox_path = ~SkitiaNPCs/Audio/Kale~
END

ADD_KIT ~X3KFK~

	~X3KFK 1 1 1 1 1 1 1 1~
 // appended column-wise to WEAPPROF.2da
//11                                T   S           F   Q             S S
//10                                W   C           L   U             W I
//9                         B L S   O   I   W       A   A             O N
//8                         A O H   H   M   A       I   R C   S       R G
//7         L S           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6         _ _       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5         S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4         W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3         O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2         R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1         D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
 ~X3KFK	    3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

 	~X3KFK 9 12 12 3 3 9~
	~X3KFK 0 0 0 0 0 0~
	~X3KFK 0 0 0 0 0 0~
    ~X3KFK 0 0 0 0 0 0~
	~X3KFK 1 1 1 1 1 1 1 1 1~
	~X3KFK 0 0 0 0 0 0~
	~%MOD_FOLDER%/2da/X3KFKcl.2da~
	~K_F_H   K_F_D  K_F_G  K_F_E  K_F_HE  K_F_HL  K_F_HO~ 
	 ~0x00000001       2~
	~FI0~
	~* * * * * * * * * * * * * * * * * * *  *~
	SAY @711
	SAY @712
	SAY @713

LAF fl#add_kit_ee


// The below sets some more variables.		
	STR_VAR
		kit_name = ~X3KFK~ // Same as your ADD KIT line. 
/* The first two lines dictate fighter thaco bonuses. You want 1 where I have both zeros for fighters to generate their bonus thaco/attacks per round. The third number is thaco penalty,
this activates on weapons you are not proficient in. Standard here is three. */
		clswpbon = ~1 0 2~		
		numwslot = ~4~ // This determines the number of non-off hand weapon slots you have. You can have up to four of these.
		hpclass = ~HPBARB~ // Bards use the rogue hit point table. You can make your own, but it's easiest to use already existing hit point progressions. 
		clsrcreq = ~1 1 1 1 1 1 1~ // This is character generation race choices.
END

// Spells 
COPY "%MOD_FOLDER%/Spells/X3KW.bam" override 
COPY "SkitiaNPCs/Spells/X3KFKS.SPL" override 
SAY NAME1 @714
SAY NAME2 @714
SAY 0x50 @715
// Store 
COPY ~%MOD_FOLDER%/Items/X3KP.STO~ override

//Items 
COPY "%MOD_FOLDER%/Items/X3KBOOK1.itm" override 
SAY NAME1 @716
SAY NAME2 @716
SAY DESC @717

COPY_EXISTING "%MOD_FOLDER%/Items/X3KCLO.itm" ~override/X3KCLO.itm~
SAY NAME1 @776
SAY NAME2 @776
SAY DESC @777
OUTER_SET strref = RESOLVE_STR_REF (@778)
APPEND item_use.2da ~X3KCLO Kale %strref% 3~

COPY "%MOD_FOLDER%/Items/X3KCHEES.itm" override 
SAY NAME1 @718
SAY NAME2 @718
SAY DESC @719

COPY "%MOD_FOLDER%/Items/X3KLET.itm" override 
SAY NAME1 @720
SAY NAME2 @720
SAY DESC @721

COPY ~%MOD_FOLDER%/items/X3KBody.itm~ ~override/X3KBody.itm~
SAY NAME1 @722
SAY NAME2 @722
SAY DESC @723

// Character SoA

COPY ~%MOD_FOLDER%/Cre/X3Kal.cre~ ~override/X3Kal.cre~
  SAY NAME1 @724
  SAY NAME2 @724
  WRITE_ASCII 0x248 ~X3Kal~ #8  //override script
  WRITE_ASCII 0x280 ~X3Kal~ #32  //DV
  WRITE_ASCII 0x2cc ~X3Kal~ #8   //pre-joining dialogue file
  WRITE_ASCII 0X34 ~X3KalM~ #8   
  WRITE_ASCII 0x3c ~X3KalL~ #8   
  SAY BIO @725
  SAY MORALE @726
  SAY HAPPY @727
  SAY UNHAPPY_ANNOYED @728
  SAY UNHAPPY_SERIOUS @729 
  SAY UNHAPPY_BREAKING_POINT ~~ // Kale's Departure is determined by Approval now.
  SAY LEADER @731
  SAY TIRED @732
  SAY BORED @733
  SAY BATTLE_CRY1 @734
  SAY BATTLE_CRY2 @735
  SAY BATTLE_CRY3 @736
  SAY BATTLE_CRY4 @737
  SAY BATTLE_CRY5 @738
  SAY DAMAGE ~~ [KaleDam]
  SAY DYING @740
  SAY HURT @741
  SAY AREA_FOREST @742
  SAY AREA_CITY @743
  SAY AREA_DUNGEON @744
  SAY AREA_DAY @745
  SAY AREA_NIGHT @746
  SAY SELECT_COMMON1 @747
  SAY SELECT_COMMON2 @748
  SAY SELECT_COMMON3 @749
  SAY SELECT_COMMON4 @750
  SAY SELECT_COMMON5 @751
  SAY SELECT_COMMON6 @752
  SAY SELECT_ACTION1 @753
  SAY SELECT_ACTION2 @754
  SAY SELECT_ACTION3 @755
  SAY SELECT_ACTION4 @756
  SAY SELECT_ACTION5 @757
  SAY SELECT_ACTION6 @758
  SAY SELECT_ACTION7 @759
  SAY CRITICAL_HIT @760
  SAY CRITICAL_MISS @761
  SAY TARGET_IMMUNE @762
  SAY INVENTORY_FULL @763
  SAY SPELL_DISRUPTED @764
  SAY SET_A_TRAP ~~ []
  SAY HIDDEN_IN_SHADOWS ~~ []
  SAY PICKED_POCKET ~~ []
  SAY SELECT_RARE1 @765
  SAY SELECT_RARE2 @751
  SAY REACT_TO_DIE_GENERAL @766 
  WRITE_SHORT 0x246 (IDS_OF_SYMBOL (~kit~ ~X3KFK~)) 

// Character ToB

COPY ~%MOD_FOLDER%/Cre/X3Kal25.cre~ ~override/X3Kal25.cre~
  SAY NAME1 @724
  SAY NAME2 @724
  WRITE_ASCII 0x248 ~X3Kal25~ #8  //override script
  WRITE_ASCII 0x280 ~X3Kal~ #32  //DV
  WRITE_ASCII 0x2cc ~X3Kal25~ #8   //pre-joining dialogue file
  WRITE_ASCII 0X34 ~X3KalM~ #8   
  WRITE_ASCII 0x3c ~X3KalL~ #8   
  SAY BIO @725
  SAY MORALE @726
  SAY HAPPY @727
  SAY UNHAPPY_ANNOYED @728
  SAY UNHAPPY_SERIOUS @729 
  SAY UNHAPPY_BREAKING_POINT ~~ // Kale's Departure is determined by Approval now.
  SAY LEADER @731
  SAY TIRED @732
  SAY BORED @733
  SAY BATTLE_CRY1 @734
  SAY BATTLE_CRY2 @735
  SAY BATTLE_CRY3 @736
  SAY BATTLE_CRY4 @737
  SAY BATTLE_CRY5 @738
  SAY DAMAGE ~~ [KaleDam]
  SAY DYING @740
  SAY HURT @741
  SAY AREA_FOREST @742
  SAY AREA_CITY @743
  SAY AREA_DUNGEON @767 
  SAY AREA_DAY @745
  SAY AREA_NIGHT @746
  SAY SELECT_COMMON1 @747
  SAY SELECT_COMMON2 @748
  SAY SELECT_COMMON3 @749
  SAY SELECT_COMMON4 @750
  SAY SELECT_COMMON5 @751
  SAY SELECT_COMMON6 @752
  SAY SELECT_ACTION1 @753
  SAY SELECT_ACTION2 @754
  SAY SELECT_ACTION3 @755
  SAY SELECT_ACTION4 @756
  SAY SELECT_ACTION5 @757
  SAY SELECT_ACTION6 @758
  SAY SELECT_ACTION7 @759
  SAY CRITICAL_HIT @760
  SAY CRITICAL_MISS @761
  SAY TARGET_IMMUNE @762
  SAY INVENTORY_FULL @763
  SAY SPELL_DISRUPTED @764
  SAY SET_A_TRAP ~~ []
  SAY HIDDEN_IN_SHADOWS ~~ []
  SAY PICKED_POCKET ~~ []
  SAY SELECT_RARE1 @765
  SAY SELECT_RARE2 @751
  SAY REACT_TO_DIE_GENERAL @766 
  WRITE_SHORT 0x246 (IDS_OF_SYMBOL (~kit~ ~X3KFK~))  
 
  APPEND ~pdialog.2da~
~X3Kal       X3KalP             X3KalJ			X3KalD~
UNLESS ~25POST~

APPEND ~pdialog.2da~
~X3Kal        X3KalP             X3KalJ            X3KalD             X3Kal25P             X3Kal25J		X3Kal25D		X3Kal25~
IF ~25POST~

APPEND ~interdia.2da~
~X3Kal       BX3Kal~
UNLESS ~25FILE~

APPEND ~interdia.2da~
~X3Kal       BX3Kal       BX3Kal25~
IF ~25FILE~ 

//Epilogues
COPY ~%MOD_FOLDER%/Epilogue/X3KalEp.2da~ ~override/X3Kal01.2da~
REPLACE ~99999~ @51

COPY ~%MOD_FOLDER%/Epilogue/X3KalEp.2da~ ~override/X3Kal02.2da~
REPLACE ~99999~ @52

COPY ~%MOD_FOLDER%/Epilogue/X3KalEp.2da~ ~override/X3KalRF.2da~
REPLACE ~99999~ @53

COPY ~%MOD_FOLDER%/Epilogue/X3KalEp.2da~ ~override/X3KalRM.2da~
REPLACE ~99999~ @54

COPY ~%MOD_FOLDER%/Epilogue/X3KalEp.2da~ ~override/X3KalRA.2da~
REPLACE ~99999~ @55


// Journal Entries 
ADD_JOURNAL TITLE (@30000) @30001 @30002 @30003 @30004 @30005 @30006 @30007 @30008 @30009 @30010 @30011 @30012 @30013 @30014 @30015 @30016 @30017 @30018 @30019 @30020 USING ~%MOD_FOLDER%/Tra/english/Kale_bg2.tra~ // The Cheeeese Quest
  
  // Portraits 
    	COPY ~%MOD_FOLDER%/Portraits/X3KalL.bmp~ ~override/X3KalL.bmp~
		COPY ~%MOD_FOLDER%/Portraits/X3KalM.bmp~ ~override/X3KalM.bmp~
COPY ~%MOD_FOLDER%/Cre/X3KJIL.cre~ ~override/X3KJIL.cre~
  WRITE_ASCII 0x248 ~X3KJIL~ #8  //override script
  WRITE_ASCII 0x280 ~X3KJIL~ #32  //DV
  WRITE_ASCII 0x2cc ~X3KJIL~ #8   // Dialogue 
  SAY NAME1 @768
  SAY NAME2 @768	
COPY ~%MOD_FOLDER%/Cre/X3KBRYCE.cre~ ~override/X3KBRYCE.cre~
  WRITE_ASCII 0x248 ~X3KBRYCE~ #8  //override script
  WRITE_ASCII 0x280 ~X3KBRYCE~ #32  //DV
  WRITE_ASCII 0x2cc ~X3KBRYCE~ #8   // Dialogue 
  SAY NAME1 @769
  SAY NAME2 @769	
COPY ~%MOD_FOLDER%/Cre/X3KC.cre~ ~override/X3KC.cre~
  WRITE_ASCII 0x248 ~X3KC~ #8  //override script
  WRITE_ASCII 0x280 ~X3KC~ #32  //DV
  WRITE_ASCII 0x2cc ~X3KC~ #8   // Dialogue 
  SAY NAME1 @770
  SAY NAME2 @770  
COPY ~%MOD_FOLDER%/Cre/X3KF.cre~ ~override/X3KF.cre~
  WRITE_ASCII 0x248 ~X3KF~ #8  //override script
  WRITE_ASCII 0x280 ~X3KF~ #32  //DV
  WRITE_ASCII 0x2cc ~X3KF~ #8   // Dialogue 
  SAY NAME1 @771
  SAY NAME2 @771   
COPY ~%MOD_FOLDER%/Cre/X3KD.cre~ ~override/X3KD.cre~
  WRITE_ASCII 0x248 ~X3KD~ #8  //override script
  WRITE_ASCII 0x280 ~X3KD~ #32  //DV
  WRITE_ASCII 0x2cc ~X3KD~ #8   // Dialogue 
  SAY NAME1 @772
  SAY NAME2 @772   
COPY ~%MOD_FOLDER%/Cre/X3KM.cre~ ~override/X3KM.cre~
  WRITE_ASCII 0x248 ~X3KM~ #8  //override script
  WRITE_ASCII 0x280 ~X3KM~ #32  //DV
  WRITE_ASCII 0x2cc ~X3KM~ #8   // Dialogue 
  SAY NAME1 @773
  SAY NAME2 @773  
COPY ~%MOD_FOLDER%/Cre/X3KMERC.cre~ ~override/X3KMERC.cre~
  WRITE_ASCII 0x248 ~X3KMERC~ #8  //override script
  WRITE_ASCII 0x280 ~X3KMERC~ #32  //DV
  WRITE_ASCII 0x2cc ~X3KMERC~ #8   // Dialogue 
  SAY NAME1 @774
  SAY NAME2 @774  
COPY ~%MOD_FOLDER%/Cre/X3KMERC2.cre~ ~override/X3KMERC2.cre~
  WRITE_ASCII 0x248 ~X3KMERC~ #8  //override script
  WRITE_ASCII 0x280 ~X3KMERC2~ #32  //DV
  WRITE_ASCII 0x2cc ~X3KMERC~ #8   // Dialogue 
  SAY NAME1 @774
  SAY NAME2 @774 
COPY ~%MOD_FOLDER%/Cre/X3KMERC3.cre~ ~override/X3KMERC3.cre~
  WRITE_ASCII 0x248 ~X3KMERC~ #8  //override script
  WRITE_ASCII 0x280 ~X3KMERC3~ #32  //DV
  WRITE_ASCII 0x2cc ~X3KMERC~ #8   // Dialogue 
  SAY NAME1 @774
  SAY NAME2 @774   
COPY ~%MOD_FOLDER%/Cre/X3KLove.cre~ ~override/X3KLove.cre~
  WRITE_ASCII 0x248 ~X3KLove~ #8  //override script
  WRITE_ASCII 0x280 ~X3KLove~ #32  //DV
  WRITE_ASCII 0x2cc ~X3KLove~ #8   // Dialogue 
  SAY NAME1 @775
  SAY NAME2 @775    
COPY ~%MOD_FOLDER%/Cre/X3KalV.cre~ ~override/X3KalV.cre~
  WRITE_ASCII 0x248 ~X3KalV~ #8  //override script
  WRITE_ASCII 0x280 ~X3KalV~ #32  //DV
  WRITE_ASCII 0x2cc ~X3KalV~ #8   // Dialogue 
  SAY NAME1 @724
  SAY NAME2 @724    
		// Creature Scripts 
COMPILE	EVALUATE_BUFFER 
~%MOD_FOLDER%/Scripts/X3Kal25.baf~ 
~%MOD_FOLDER%/Scripts/X3Kal.baf~ 
~%MOD_FOLDER%/Scripts/X3KalD.baf~ 
~%MOD_FOLDER%/Scripts/X3KReset.baf~ 
~%MOD_FOLDER%/Scripts/X3KJIL.baf~ 
~%MOD_FOLDER%/Scripts/X3KBRYCE.baf~ 
~%MOD_FOLDER%/Scripts/X3KC.baf~ 
~%MOD_FOLDER%/Scripts/X3KBodhi.baf~ 
~%MOD_FOLDER%/Scripts/X3KalV.baf~ 
~%MOD_FOLDER%/Scripts/X3KW1.baf~ 
// Area Scripts 
 COPY_EXISTING ~AR0332.are~ ~override~
      WRITE_ASCII 0x94 ~AR0332~ #8 
COMPILE ~%MOD_FOLDER%/Scripts/AR0332.baf~	
 EXTEND_BOTTOM ~ar0500.bcs~ ~%MOD_FOLDER%/Scripts/ar0500.baf~
 EXTEND_TOP ~CLEANSE.bcs~ ~%MOD_FOLDER%/Scripts/CLEANSE.baf~
  EXTEND_BOTTOM ~ar0400.bcs~ ~%MOD_FOLDER%/Scripts/ar0400.baf~
  // There is no AR0332 file. To get around that, we have NPCs spawn in 300 and move to the 332 area.
 EXTEND_BOTTOM ~ar0300.bcs~ ~%MOD_FOLDER%/Scripts/ar0300.baf~
//Dialogue 
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/dialogue/X3Kal.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3Kal.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/dialogue/X3Kal25.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3Kal25.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/dialogue/X3KF.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3KF.tra~ // Flora 
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/dialogue/X3KBRYCE.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3KBRYCE.tra~ // Bryce 
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/dialogue/X3KC.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3KC.tra~ // Chester  
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/dialogue/X3KM.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3KM.tra~ // Martin 
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/dialogue/X3KD.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3KD.tra~ // Dallie 
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/dialogue/X3KJIL.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3KJIL.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/dialogue/BX3Kal.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/BX3Kal.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/dialogue/BX3Kal25.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/BX3Kal25.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/dialogue/X3KalJ.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3KalJ.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/dialogue/X3Kal25J.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3Kal25J.tra~



