LOAD_TRA ~%MOD_FOLDER%/Tra/English/KALE_bg2.tra~
LAF HANDLE_AUDIO
  STR_VAR
    audio_path = ~SkitiaNPCs/Audio/Kale~
    oggdec_path = ~SkitiaNPCs/Audio~
    sox_path = ~SkitiaNPCs/Audio/Kale~
END

ADD_KIT ~X3KFK~

	~X3KFK 1 1 1 1 1 1 1 1~
 // appended column-wise to WEAPPROF.2da
//11                                T   S           F   Q             S S
//10                                W   C           L   U             W I
//9                         B L S   O   I   W       A   A             O N
//8                         A O H   H   M   A       I   R C   S       R G
//7         L S           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6         _ _       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5         S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4         W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3         O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2         R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1         D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
 ~X3KFK	    3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

 	~X3KFK 9 12 12 3 3 9~
	~X3KFK 0 0 0 0 0 0~
	~X3KFK 0 0 0 0 0 0~
    ~X3KFK 0 0 0 0 0 0~
	~X3KFK 1 1 1 1 1 1 1 1 1~
	~X3KFK 0 0 0 0 0 0~
	~%MOD_FOLDER%/2da/X3KFKcl.2da~
	~K_F_H   K_F_D  K_F_G  K_F_E  K_F_HE  K_F_HL  K_F_HO~ 
	 ~0x00000001       2~
	~FI0~
	~* * * * * * * * * * * * * * * * * * *  *~
	SAY ~warden~
	SAY ~Warden~
	SAY ~WARDEN: The warden is a warrior whose discipline and traditions center around fighting in pairs. The warden takes on the defensive role in the pair, while the ward receives elevated offensive prowess. Their remarkable protective talents come at the cost of the warden’s skill with weapons being inferior to other fighter traditions.
	
	Advantages:
	-Hit Die: d12
	-May use the Ward ability once per day. Gains one use at level 1, one use at level eight, and an additional use every eight levels thereafter.
	
	WARD: Designates target as the ward for one turn. It does not stack with itself, and if the ward is changed, the previous ward loses their bonuses. 
	Level 1: The ward receives +1 damage bonus and -1 THAC0. The warden receives penalties for the same amount, but gains 10% resistance to physical damage and regenerates 1 hitpoint per 6 seconds.
	Level 8: The ward receives +2 damage bonus and -2 THAC0. The warden receives penalties for the same amount, but gains 20% resistance to physical damage, and regenerates 1 hitpoint per 3 seconds.
	Level 16: The ward receives +3 damage bonus and -3 THAC0. The warden receives penalties for the same amount, but gains 30% resistance to physical damage and regenerates 1 hitpoint per second.

	Disadvantages:
	May only become specialized in ranged weapons, and may not exceed mastery in any other weapon.~

LAF fl#add_kit_ee


// The below sets some more variables.		
	STR_VAR
		kit_name = ~X3KFK~ // Same as your ADD KIT line. 
/* The first two lines dictate fighter thaco bonuses. You want 1 where I have both zeros for fighters to generate their bonus thaco/attacks per round. The third number is thaco penalty,
this activates on weapons you are not proficient in. Standard here is three. */
		clswpbon = ~1 0 2~		
		numwslot = ~4~ // This determines the number of non-off hand weapon slots you have. You can have up to four of these.
		hpclass = ~HPBARB~ // Bards use the rogue hit point table. You can make your own, but it's easiest to use already existing hit point progressions. 
		clsrcreq = ~1 1 1 1 1 1 1~ // This is character generation race choices.
END

// Spells 
COPY "%MOD_FOLDER%/Spells/X3KW.bam" override 
COPY "SkitiaNPCs/Spells/X3KFKS.SPL" override 
SAY NAME1 ~Ward~
SAY NAME2 ~Ward~
SAY DESC ~WARD: Designates target as the ward for one turn. It does not stack with itself, and if the ward is changed, the previous ward loses their bonuses. 
Level 1: The ward receives +1 damage bonus and -1 THAC0. The warden receives penalties for the same amount, but gains 10% resistance to physical damage and regenerates 1 hitpoint per 6 seconds.
Level 8: The ward receives +2 damage bonus and -2 THAC0. The warden receives penalties for the same amount, but gains 20% resistance to physical damage, and regenerates 1 hitpoint per 3 seconds.
Level 16: The ward receives +3 damage bonus and -3 THAC0. The warden receives penalties for the same amount, but gains 30% resistance to physical damage and regenerates 1 hitpoint per second.
~
// Store 
COPY ~%MOD_FOLDER%/Items/X3KP.STO~ override

//Items 
COPY "%MOD_FOLDER%/Items/X3KBOOK1.itm" override 
SAY NAME1 ~Kale's Father's Journal~
SAY NAME2 ~Kale's Father's Journal~
SAY DESC ~The journal mostly contains details of shopping checklists and dry details of Percy's life. The last few entries however contain some interesting details of note.

"Got in trouble with the guard Bryce again when I got in a scuffle with that awful beggar Martin in the docks. He's always watching from the docks. Got something against halflings, I know he must. When I said I didn't have enough money for his stupid fine over fishing around the docks, I spent a few lousy nights in jail. And that Martin got nothing at all.
Sometimes I think I ought to go wandering again, this city is suffocating my feet. Jillian was the only honest guard member of the docks garrision, but it's not work for a halfling, not with people like Bryce working for them, and she was right to go back wandering with an adventure. She said my son is amongst the adventuring group she is joining.
I ought to introduce myself, but I just can't."

"Chester started selling some new cheese in his cheese shop. Damn it tastes good. Like nothing I've ever had before. Definitely making it a daily addition for my shopping list when I go out and get food."

"Cheese. Cheeeeese. Cheeeeeeeese. I bought up all of the cheese. I promised I'd pay it in full once I had a little bit more money, but Chester doesn't seem to mind at all. What a friendly fellow. Dallie's been getting a bit upset though, that I've been paying more attention to the food than her.
At least she doesn't know about Flora too. I know it's wrong. I know we had a handfasting planned and everything soon, but I love both woman. One for her heart and the other for her appeareance blessed by Sheela herself. What's wrong with playing my luck for a little longer?"

"Money's getting low and Dallie is really getting angry at the stockpile of cheese I got. She won't even taste it despite my protests, she knows it smells good. This stuff is gold. It's worth it all. It's cheeeese. It's heaven. It's amazing.
Even Flora's gotten a bit concerned. She's asking when I'm going to leave her. I don't want to leave anyone. I love Dallie. I love Flora. And I love this cheese too. Just got to enjoy everything while it lasts."

"I think someone's trying to kill me. I feel god awful inside these last few days. I should see a priest, but Chester's amazing cheese always makes me feel a bit happier inside. Just going to buy a bit more before I go off to the church of Ilmater, they're kindly folks there, and I trust them more than anyone.
I'll give Martin a good insult on the way too. He deserves it for getting me in a cell for too many miserable nights."

STATISTICS:

Weight: 1~

COPY "%MOD_FOLDER%/Items/X3KCHEES.itm" override 
SAY NAME1 ~Bag of Strange Cheese~
SAY NAME2 ~Bag of Strange Cheese~
SAY DESC ~This cheese smells and looks odd to non-halflings, and has no direct impact to them if eaten. But to a halfling, it smells quite pleasing with an inviting aroma.

STATISTICS: 

Weight: 1~

COPY "%MOD_FOLDER%/Items/X3KLET.itm" override 
SAY NAME1 ~Letter~
SAY NAME2 ~Letter~
SAY DESC ~I have been alerted that there will be an attempted arrest on my person. Your pay is attached to this letter, and you will receive an additional sum upon completion of the task.
When you have succesfully terminated the halfling and her puppets, return to my home on the northside of the bridge district.

Chester~

COPY ~%MOD_FOLDER%/items/X3KBody.itm~ ~override/X3KBody.itm~
SAY NAME1 ~Kale's Body~
SAY NAME2 ~Kale's Body~
SAY DESC ~Kale was captured by Bodhi and infected with vampirism, forcing you to slay him. There may be some way to revive him, though you don't know what it would be.

STATISTICS:

Weight: 40~

// Character SoA

COPY ~%MOD_FOLDER%/Cre/X3Kal.cre~ ~override/X3Kal.cre~
  SAY NAME1 ~Kale~
  SAY NAME2 ~Kale~
  WRITE_ASCII 0x248 ~X3Kal~ #8  //override script
  WRITE_ASCII 0x280 ~X3Kal~ #32  //DV
  WRITE_ASCII 0x2cc ~X3Kal~ #8   //pre-joining dialogue file
  WRITE_ASCII 0X34 ~X3KalM~ #8   
  WRITE_ASCII 0x3c ~X3KalL~ #8   
  SAY BIO ~Kale gives a wide grin when you ask about himself, clapping you on your back and launching straight into his tale. He claims he was born faster, stronger, and with more courage in his spirit than all the halflings of Gullykin combined. He flashes scars and launches into wild, eyebrow raising tales of how he earned each, from battling one hundred kobolds alone to slapping a dragon in the face.  But after a while he grows melancholy and admits that in all of his travels he has lost many companions that he would dearly miss. He says he has changed his style of fighting to be more protective of those he cares about. He'll take any blow for a companion if that means they'll keep standing, if he likes them anyway.
"But the rest?" He adds with a grin once more. "They'll have give me a good offer."~
  SAY MORALE ~This isn't working out like I thought.~ [KaleFlee]
  SAY HAPPY ~I feel better than a fox with a belly full of chicken! Not bloody bad at all.~ [KaleHap]
  SAY UNHAPPY_ANNOYED ~Things aren't all bad, but they aren't all great either.~
  SAY UNHAPPY_SERIOUS ~I ain't pleased with what's going on. Get your head on straight, mate, or you'll lose your best talent.~ 
  SAY UNHAPPY_BREAKING_POINT ~~ // Kale's Departure is determined by Approval now.
  SAY LEADER ~Oy, listen up!~ [KaleLead]
  SAY TIRED ~I am so bushed, you have no idea.~ [KaleRest]
  SAY BORED ~*Yawn*~ [KaleBore]
  SAY BATTLE_CRY1 ~Okay, now you're in for it.~ [X3KCry1]
  SAY BATTLE_CRY2 ~Here comes halfling death!~ [KaleCry2]
  SAY BATTLE_CRY3 ~Let's have a bit of fun, shall we?~ [X3KCry2]
  SAY BATTLE_CRY4 ~Now you're gonna get it!~ [KaleCry4]
  SAY BATTLE_CRY5 ~Uh oh. Uninvited guests.~ [KaleCry5]
  SAY DAMAGE ~~ [KaleDam]
  SAY DYING ~Aww, not again...~ [KaleDead]
  SAY HURT ~Hey, bleeding over here!~ [KaleHurt]
  SAY AREA_FOREST ~Oh lovely. What'd I step in now?~ [KaleFor]
  SAY AREA_CITY ~I thought it would be a bit smaller, myself.~ [X3KCity]
  SAY AREA_DUNGEON ~Oi, what's that? Oh...just another rat.~ [KaleDun]
  SAY AREA_DAY ~Sooo. I wonder how much a map of this place would go for?~ [KaleDay]
  SAY AREA_NIGHT ~Criminy. Where the bloody hell are we?~ [KaleNigh]
  SAY SELECT_COMMON1 ~Yeah? You want something, I bet.~  [KaleCom1]
  SAY SELECT_COMMON2 ~Aye now. Something else you need?~ [KaleCom2]
  SAY SELECT_COMMON3 ~Soooo.~ [KaleCom3]
  SAY SELECT_COMMON4 ~Yep?~ [KaleCom4]
  SAY SELECT_COMMON5 ~Come on, come on!~ [KaleCom5]
  SAY SELECT_COMMON6 ~Righto. Off we go.~ [KaleAct1]
  SAY SELECT_ACTION1 ~Okey-Dokey.~ [KaleAct2]
  SAY SELECT_ACTION2 ~Wish I thought of that.~ [KaleAct3]
  SAY SELECT_ACTION3 ~Just give me a sec.~ [KaleAct4]
  SAY SELECT_ACTION4 ~You might want to re-think that.~ [KaleAct5]
  SAY SELECT_ACTION5 ~Woohoo.~ [KaleAct6]
  SAY SELECT_ACTION6 ~Aye.~ [X3KAye]
  SAY SELECT_ACTION7 ~Sooo.~ [X3KSo]
  SAY CRITICAL_HIT ~Yeah! That's the way!~ [KaleCrit]
  SAY CRITICAL_MISS ~Damn it!~ [X3KCrtM]
  SAY TARGET_IMMUNE ~I ain't doing much here.~ [KaleImm]
  SAY INVENTORY_FULL ~What am I, a bloody mule?!~  [KaleInv]
  SAY SPELL_DISRUPTED ~I hate it when my bloody spells won't work.~ [KaleSpel]
  SAY SET_A_TRAP ~~ []
  SAY HIDDEN_IN_SHADOWS ~~ []
  SAY PICKED_POCKET ~~ []
  SAY SELECT_RARE1 ~Oh um. Maybe we should organize ourselves a bit?~ [KaleRare]
  SAY SELECT_RARE2 ~Come on, come on!~ [KaleCom5]
  SAY REACT_TO_DIE_GENERAL ~Oh shoot. And we were doing so well...~ [KaleDieR] 
  WRITE_SHORT 0x246 (IDS_OF_SYMBOL (~kit~ ~X3KFK~)) 

// Character ToB

COPY ~%MOD_FOLDER%/Cre/X3Kal25.cre~ ~override/X3Kal25.cre~
  SAY NAME1 ~Kale~
  SAY NAME2 ~Kale~
  WRITE_ASCII 0x248 ~X3Kal25~ #8  //override script
  WRITE_ASCII 0x280 ~X3Kal~ #32  //DV
  WRITE_ASCII 0x2cc ~X3Kal25~ #8   //pre-joining dialogue file
  WRITE_ASCII 0X34 ~X3KalM~ #8   
  WRITE_ASCII 0x3c ~X3KalL~ #8   
  SAY BIO ~Kale gives a wide grin when you ask about himself, clapping you on your back and launching straight into his tale. He claims he was born faster, stronger, and with more courage in his spirit than all the halflings of Gullykin combined. He flashes scars and launches into wild, eyebrow raising tales of how he earned each, from battling one hundred kobolds alone to slapping a dragon in the face.  But after a while he grows melancholy and admits that in all of his travels he has lost many companions that he would dearly miss. He says he has changed his style of fighting to be more protective of those he cares about. He'll take any blow for a companion if that means they'll keep standing, if he likes them anyway.
"But the rest?" He adds with a grin once more. "They'll have give me a good offer."~
  SAY MORALE ~This isn't working out like I thought.~ [KaleFlee]
  SAY HAPPY ~I feel better than a fox with a belly full of chicken! Not bloody bad at all.~ [KaleHap]
  SAY UNHAPPY_ANNOYED ~Things aren't all bad, but they aren't all great either.~
  SAY UNHAPPY_SERIOUS ~I ain't pleased with what's going on. Get your head on straight, mate, or you'll lose your best talent.~ 
  SAY UNHAPPY_BREAKING_POINT ~~ // Kale's Departure is determined by Approval now.
  SAY LEADER ~Oy, listen up!~ [KaleLead]
  SAY TIRED ~I am so bushed, you have no idea.~ [KaleRest]
  SAY BORED ~*Yawn*~ [KaleBore]
  SAY BATTLE_CRY1 ~Okay, now you're in for it.~ [X3KCry1]
  SAY BATTLE_CRY2 ~Here comes halfling death!~ [KaleCry2]
  SAY BATTLE_CRY3 ~Let's have a bit of fun, shall we?~ [X3KCry2]
  SAY BATTLE_CRY4 ~Now you're gonna get it!~ [KaleCry4]
  SAY BATTLE_CRY5 ~Uh oh. Uninvited guests.~ [KaleCry5]
  SAY DAMAGE ~~ [KaleDam]
  SAY DYING ~Aww, not again...~ [KaleDead]
  SAY HURT ~Hey, bleeding over here!~ [KaleHurt]
  SAY AREA_FOREST ~Oh lovely. What'd I step in now?~ [KaleFor]
  SAY AREA_CITY ~I thought it would be a bit smaller, myself.~ [X3KCity]
  SAY AREA_DUNGEON ~Oi, what's that? Oh...just another rat.~ 
  SAY AREA_DAY ~Sooo. I wonder how much a map of this place would go for?~ [KaleDay]
  SAY AREA_NIGHT ~Criminy. Where the bloody hell are we?~ [KaleNigh]
  SAY SELECT_COMMON1 ~Yeah? You want something, I bet.~  [KaleCom1]
  SAY SELECT_COMMON2 ~Aye now. Something else you need?~ [KaleCom2]
  SAY SELECT_COMMON3 ~Soooo.~ [KaleCom3]
  SAY SELECT_COMMON4 ~Yep?~ [KaleCom4]
  SAY SELECT_COMMON5 ~Come on, come on!~ [KaleCom5]
  SAY SELECT_COMMON6 ~Righto. Off we go.~ [KaleAct1]
  SAY SELECT_ACTION1 ~Okey-Dokey.~ [KaleAct2]
  SAY SELECT_ACTION2 ~Wish I thought of that.~ [KaleAct3]
  SAY SELECT_ACTION3 ~Just give me a sec.~ [KaleAct4]
  SAY SELECT_ACTION4 ~You might want to re-think that.~ [KaleAct5]
  SAY SELECT_ACTION5 ~Woohoo.~ [KaleAct6]
  SAY SELECT_ACTION6 ~Aye.~ [X3KAye]
  SAY SELECT_ACTION7 ~Sooo.~ [X3KSo]
  SAY CRITICAL_HIT ~Yeah! That's the way!~ [KaleCrit]
  SAY CRITICAL_MISS ~Damn it!~ [X3KCrtM]
  SAY TARGET_IMMUNE ~I ain't doing much here.~ [KaleImm]
  SAY INVENTORY_FULL ~What am I, a bloody mule?!~  [KaleInv]
  SAY SPELL_DISRUPTED ~I hate it when my bloody spells won't work.~ [KaleSpel]
  SAY SET_A_TRAP ~~ []
  SAY HIDDEN_IN_SHADOWS ~~ []
  SAY PICKED_POCKET ~~ []
  SAY SELECT_RARE1 ~Oh um. Maybe we should organize ourselves a bit?~ [KaleRare]
  SAY SELECT_RARE2 ~Come on, come on!~ [KaleCom5]
  SAY REACT_TO_DIE_GENERAL ~Oh shoot. And we were doing so well...~ [KaleDieR] 
  WRITE_SHORT 0x246 (IDS_OF_SYMBOL (~kit~ ~X3KFK~))  
 
  APPEND ~pdialog.2da~
~X3Kal       X3KalP             X3KalJ			X3KalD~
UNLESS ~X3Kal ~
UNLESS ~25POST~

APPEND ~pdialog.2da~
~X3Kal        X3KalP             X3KalJ            X3KalD             X3Kal25P             X3Kal25J		X3Kal25D		X3Kal25~
UNLESS ~X3Kal~
IF ~25POST~

APPEND ~interdia.2da~
~X3Kal       BX3Kal~
UNLESS ~X3Kal~
UNLESS ~25FILE~

APPEND ~interdia.2da~
~X3Kal       BX3Kal       BX3Kal25~
UNLESS ~X3Kal~
IF ~25FILE~ 

//Epilogues
COPY ~%MOD_FOLDER%/Epilogue/X3KalEp.2da~ ~override/X3Kal01.2da~
REPLACE ~99999~ @51

COPY ~%MOD_FOLDER%/Epilogue/X3KalEp.2da~ ~override/X3Kal02.2da~
REPLACE ~99999~ @52

COPY ~%MOD_FOLDER%/Epilogue/X3KalEp.2da~ ~override/X3KalRF.2da~
REPLACE ~99999~ @53

COPY ~%MOD_FOLDER%/Epilogue/X3KalEp.2da~ ~override/X3KalRM.2da~
REPLACE ~99999~ @54

COPY ~%MOD_FOLDER%/Epilogue/X3KalEp.2da~ ~override/X3KalRA.2da~
REPLACE ~99999~ @55


// Journal Entries 
ADD_JOURNAL TITLE (@0) @1 @2 @3 @4 @5 @6 @7 @8 @9 @10 @11 @12 @13 @14 @15 @16 @17 @18 USING ~%MOD_FOLDER%/Tra/english/Kale_bg2.tra~ // The Cheeeese Quest
  
  // Portraits 
    	COPY ~%MOD_FOLDER%/Portraits/X3KalL.bmp~ ~override/X3KalL.bmp~
		COPY ~%MOD_FOLDER%/Portraits/X3KalM.bmp~ ~override/X3KalM.bmp~
COPY ~%MOD_FOLDER%/Cre/X3KJIL.cre~ ~override/X3KJIL.cre~
  WRITE_ASCII 0x248 ~X3KJIL~ #8  //override script
  WRITE_ASCII 0x280 ~X3KJIL~ #32  //DV
  WRITE_ASCII 0x2cc ~X3KJIL~ #8   // Dialogue 
  SAY NAME1 ~Jillian~
  SAY NAME2 ~Jillian~	
COPY ~%MOD_FOLDER%/Cre/X3KBRYCE.cre~ ~override/X3KBRYCE.cre~
  WRITE_ASCII 0x248 ~X3KBRYCE~ #8  //override script
  WRITE_ASCII 0x280 ~X3KBRYCE~ #32  //DV
  WRITE_ASCII 0x2cc ~X3KBRYCE~ #8   // Dialogue 
  SAY NAME1 ~Sergeant Bryce~
  SAY NAME2 ~Sergeant Bryce~	
COPY ~%MOD_FOLDER%/Cre/X3KC.cre~ ~override/X3KC.cre~
  WRITE_ASCII 0x248 ~X3KC~ #8  //override script
  WRITE_ASCII 0x280 ~X3KC~ #32  //DV
  WRITE_ASCII 0x2cc ~X3KC~ #8   // Dialogue 
  SAY NAME1 ~Chester~
  SAY NAME2 ~Chester~  
COPY ~%MOD_FOLDER%/Cre/X3KF.cre~ ~override/X3KF.cre~
  WRITE_ASCII 0x248 ~X3KF~ #8  //override script
  WRITE_ASCII 0x280 ~X3KF~ #32  //DV
  WRITE_ASCII 0x2cc ~X3KF~ #8   // Dialogue 
  SAY NAME1 ~Flora~
  SAY NAME2 ~Flora~   
COPY ~%MOD_FOLDER%/Cre/X3KD.cre~ ~override/X3KD.cre~
  WRITE_ASCII 0x248 ~X3KD~ #8  //override script
  WRITE_ASCII 0x280 ~X3KD~ #32  //DV
  WRITE_ASCII 0x2cc ~X3KD~ #8   // Dialogue 
  SAY NAME1 ~Dallie~
  SAY NAME2 ~Dallie~   
COPY ~%MOD_FOLDER%/Cre/X3KM.cre~ ~override/X3KM.cre~
  WRITE_ASCII 0x248 ~X3KM~ #8  //override script
  WRITE_ASCII 0x280 ~X3KM~ #32  //DV
  WRITE_ASCII 0x2cc ~X3KM~ #8   // Dialogue 
  SAY NAME1 ~Martin~
  SAY NAME2 ~Martin~  
COPY ~%MOD_FOLDER%/Cre/X3KMERC.cre~ ~override/X3KMERC.cre~
  WRITE_ASCII 0x248 ~X3KMERC~ #8  //override script
  WRITE_ASCII 0x280 ~X3KMERC~ #32  //DV
  WRITE_ASCII 0x2cc ~X3KMERC~ #8   // Dialogue 
  SAY NAME1 ~Mercenary~
  SAY NAME2 ~Mercenary~  
COPY ~%MOD_FOLDER%/Cre/X3KMERC2.cre~ ~override/X3KMERC2.cre~
  WRITE_ASCII 0x248 ~X3KMERC~ #8  //override script
  WRITE_ASCII 0x280 ~X3KMERC2~ #32  //DV
  WRITE_ASCII 0x2cc ~X3KMERC~ #8   // Dialogue 
  SAY NAME1 ~Mercenary~
  SAY NAME2 ~Mercenary~ 
COPY ~%MOD_FOLDER%/Cre/X3KMERC3.cre~ ~override/X3KMERC3.cre~
  WRITE_ASCII 0x248 ~X3KMERC~ #8  //override script
  WRITE_ASCII 0x280 ~X3KMERC3~ #32  //DV
  WRITE_ASCII 0x2cc ~X3KMERC~ #8   // Dialogue 
  SAY NAME1 ~Mercenary~
  SAY NAME2 ~Mercenary~   
COPY ~%MOD_FOLDER%/Cre/X3KLove.cre~ ~override/X3KLove.cre~
  WRITE_ASCII 0x248 ~X3KLove~ #8  //override script
  WRITE_ASCII 0x280 ~X3KLove~ #32  //DV
  WRITE_ASCII 0x2cc ~X3KLove~ #8   // Dialogue 
  SAY NAME1 ~Alora~
  SAY NAME2 ~Alora~    
COPY ~%MOD_FOLDER%/Cre/X3KalV.cre~ ~override/X3KalV.cre~
  WRITE_ASCII 0x248 ~X3KalV~ #8  //override script
  WRITE_ASCII 0x280 ~X3KalV~ #32  //DV
  WRITE_ASCII 0x2cc ~X3KalV~ #8   // Dialogue 
  SAY NAME1 ~Kale~
  SAY NAME2 ~Kale~    
		// Creature Scripts 
COMPILE	EVALUATE_BUFFER 
~%MOD_FOLDER%/Scripts/X3Kal25.baf~ 
~%MOD_FOLDER%/Scripts/X3Kal.baf~ 
~%MOD_FOLDER%/Scripts/X3KalD.baf~ 
~%MOD_FOLDER%/Scripts/X3KJIL.baf~ 
~%MOD_FOLDER%/Scripts/X3KBRYCE.baf~ 
~%MOD_FOLDER%/Scripts/X3KC.baf~ 
~%MOD_FOLDER%/Scripts/X3KBodhi.baf~ 
~%MOD_FOLDER%/Scripts/X3KalV.baf~ 
~%MOD_FOLDER%/Scripts/X3KW1.baf~ 
// Area Scripts 
 EXTEND_BOTTOM ~ar0500.bcs~ ~%MOD_FOLDER%/Scripts/ar0500.baf~
 EXTEND_TOP ~CLEANSE.bcs~ ~%MOD_FOLDER%/Scripts/CLEANSE.baf~
  EXTEND_BOTTOM ~ar0400.bcs~ ~%MOD_FOLDER%/Scripts/ar0400.baf~
  // There is no AR0332 file. To get around that, we have NPCs spawn in 300 and move to the 332 area.
 EXTEND_BOTTOM ~ar0300.bcs~ ~%MOD_FOLDER%/Scripts/ar0300.baf~
//Dialogue 
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/dialogue/X3Kal.d~
~%MOD_FOLDER%/dialogue/X3Kal25.d~
~%MOD_FOLDER%/dialogue/X3KJIL.d~
~%MOD_FOLDER%/dialogue/X3KBRYCE.d~ // Bryce 
~%MOD_FOLDER%/dialogue/X3KC.d~ // Chester  
~%MOD_FOLDER%/dialogue/X3KM.d~ // Martin 
~%MOD_FOLDER%/dialogue/X3KF.d~ // Flora 
~%MOD_FOLDER%/dialogue/X3KD.d~ // Dallie 
~%MOD_FOLDER%/dialogue/BX3Kal.d~
~%MOD_FOLDER%/dialogue/BX3Kal25.d~
~%MOD_FOLDER%/dialogue/X3KalJ.d~
~%MOD_FOLDER%/dialogue/X3Kal25J.d~



