LOAD_TRA ~%MOD_FOLDER%/Tra/%LANGUAGE%/RECORDER_bg2.tra~

LAF HANDLE_AUDIO
  STR_VAR
    audio_path = ~SkitiaNPCs/Audio/Recorder~
    oggdec_path = ~SkitiaNPCs/Audio~
    sox_path = ~SkitiaNPCs/Audio/Recorder~
END


ADD_KIT ~X3Bard~
	~X3Bard 1 1 1 1 1 1 1 1~
 // appended column-wise to WEAPPROF.2da
//11                                T   S           F   Q             S S
//10                                W   C           L   U             W I
//9                         B L S   O   I   W       A   A             O N
//8                         A O H   H   M   A       I   R C   S       R G
//7         L S           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6         _ _       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5         S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4         W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3         O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2         R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1         D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
 ~X3Bard	0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

 	~X3Bard 3 3 3 12 12 3~
	~X3Bard 0 0 0 0 0 0~
	~X3Bard 0 0 0 0 0 0~
    ~X3Bard 0 0 0 17 17 0~
	~X3Bard 1 1 1 1 1 1 1 1 1~
	~X3Bard 1 1 1 1 0 0~
	~%MOD_FOLDER%/2da/X3Bardcl.2da~
	~~ 
	~0x00080000 5~
	~X3R~
	~* * * * * * * * * * * * * * * * * * *  *~
	SAY @776
	SAY @777
	SAY @778

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~X3Bard~ 
		clswpbon = ~0 0 3~		
		numwslot = ~2~ // This determines the number of non-off hand weapon slots you have. You can have up to four of these, though mages/bards/thieves have two, so we picked two.
		thiefscl = ~0 0 0 0 0 0 0 0~
		hpclass = ~HPROG~ // Bards use the rogue hit point table. You can make your own, but it's easiest to use already existing hit point progressions. 
		clsrcreq = ~1 1 1 1 1 1 1~ // This is CHARGEN choices.
		clasthac = ~0~
END
//HLA 
COPY	"%MOD_FOLDER%/2da/LUX3R.2da" override
//Spell
COPY	"%MOD_FOLDER%/Spells/x3rpkit.spl" override
COPY	"%MOD_FOLDER%/Spells/x3rpkit3.spl" override
COPY    "%MOD_FOLDER%/Spells/X3RBS.bam" override 
COPY    "%MOD_FOLDER%/Spells/X3RHLA.spl" override 
SAY NAME1 @779
SAY NAME2 @779
SAY 0x50 @780
COPY    "%MOD_FOLDER%/Spells/X3RHLAS.spl" override 
SAY NAME1 @779
SAY NAME2 @779
SAY 0x50 @781
COPY	"%MOD_FOLDER%/Spells/x3rpkit2.spl" override
	SAY NAME1 @782
	SAY NAME2 @782
	SAY 0x50 @783

COPY	"%MOD_FOLDER%/Spells/x3rpkit4.spl" override
	SAY NAME1 @782
	SAY NAME2 @782
	SAY 0x50 @783

COPY "%MOD_FOLDER%/Spells/X3RSum.SPL" override 
SAY NAME1 @784
SAY NAME2 @784
SAY 0x50 @785

COPY "%MOD_FOLDER%/Spells/X3RDOOR.SPL" override 
SAY NAME1 @786
SAY NAME2 @786
SAY DESC @787


//Items 
COPY	"%MOD_FOLDER%/Items/CX3BRD02.bam" override
COPY	"%MOD_FOLDER%/Items/IX3BRD02.bam" override
COPY	"%MOD_FOLDER%/Items/X3RFlute.itm" override
SAY NAME1 @788
SAY NAME2 @788
SAY DESC  @789
    LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (@790)
	STR_VAR
	  resource = X3Reb
END	

	  
COPY "%MOD_FOLDER%/Items/X3Rfer.itm" override 
SAY NAME1 @791
SAY NAME2 @791
SAY DESC @792
	OUTER_SET strref = RESOLVE_STR_REF (@793)
	APPEND item_use.2da ~X3RFER Recorder %strref% 3~

COPY "%MOD_FOLDER%/Items/X3RARM.bam" override 
COPY "%MOD_FOLDER%/Items/X3RLEAT.itm" override 
SAY NAME1 @794
SAY NAME2 @794
SAY DESC @795  

COPY "%MOD_FOLDER%/Items/X3RBOUNT.itm" override 
SAY NAME1 @796 
SAY NAME2 @796 
SAY DESC @797
COPY "%MOD_FOLDER%/Items/X3RNOTE.itm" override 
SAY NAME1 @798 
SAY NAME2 @798 
SAY DESC @799
COPY "%MOD_FOLDER%/Items/X3RSCI.itm" override 
SAY NAME1 @800 
SAY NAME2 @800 
SAY DESC @801

COPY ~%MOD_FOLDER%/items/X3RBody.bam~ ~override/X3RBody.bam~
COPY ~%MOD_FOLDER%/items/X3RBody.itm~ ~override/X3RBody.itm~
SAY NAME1 @802
SAY NAME2 @802
SAY DESC @803

COPY ~%MOD_FOLDER%/items/X3RGEM.itm~ ~override/X3RGEM.itm~
SAY NAME1 @804
SAY NAME2 @804
SAY DESC @805

COPY_EXISTING ~%MOD_FOLDER%/Items/x3RingR.itm~ ~override/x3RingR.itm~
SAY NAME1 @806
SAY NAME2 @806
SAY DESC @807 
    LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter2 = 11
	  power = 1
	  special = RESOLVE_STR_REF (@790)
	STR_VAR
	  resource = X3Reb
END

// Character SoA 
COPY ~%MOD_FOLDER%/Cre/X3Reb.cre~ ~override/X3Reb.cre~
  SAY NAME1 @790
  SAY NAME2 @790
  WRITE_ASCII 0x248 ~X3Reb~ #8  //override script
  WRITE_ASCII 0x280 ~X3Reb~ #32  //DV
  WRITE_ASCII 0x2cc ~X3Reb~ #8   //pre-joining dialogue file
  WRITE_ASCII 0X34 ~X3RebM~ #8   
  WRITE_ASCII 0x3c ~X3RebL~ #8  
  SAY BIO @808
  SAY INITIAL_MEETING @809
  SAY MORALE @810 
  SAY HAPPY  @811
  SAY UNHAPPY_ANNOYED @812
  SAY UNHAPPY_SERIOUS @813
  SAY UNHAPPY_BREAKING_POINT ~~ [] 
  SAY LEADER @815
  SAY TIRED @816
  SAY BORED @817
  SAY BATTLE_CRY1 @818
  SAY BATTLE_CRY2 @819
  SAY BATTLE_CRY3 @820
  SAY BATTLE_CRY4 @821
  SAY BATTLE_CRY5 @822
  SAY DAMAGE ~~ [X3RDam]
  SAY DYING ~~ [X3RDead]
  SAY HURT @825
  SAY AREA_FOREST @826
  SAY AREA_CITY @827
  SAY AREA_DUNGEON @828
  SAY AREA_DAY @829
  SAY AREA_NIGHT @830
  SAY SELECT_COMMON1 @831
  SAY SELECT_COMMON2 @832
  SAY SELECT_COMMON3 @833
  SAY SELECT_COMMON4 @834
  SAY SELECT_COMMON5 @835
  SAY SELECT_COMMON6 @836
  SAY SELECT_ACTION1 @837
  SAY SELECT_ACTION2 @838
  SAY SELECT_ACTION3 @839
  SAY SELECT_ACTION4 @840
  SAY SELECT_ACTION5 @841
  SAY SELECT_ACTION6 @842
  SAY SELECT_ACTION7 @832
  SAY SELECT_ACTION7 @843
  SAY CRITICAL_HIT @844
  SAY CRITICAL_MISS @845
  SAY TARGET_IMMUNE @846
  SAY INVENTORY_FULL @847
  SAY SPELL_DISRUPTED @848
  SAY SET_A_TRAP ~~ []
  SAY HIDDEN_IN_SHADOWS ~~ []
  SAY PICKED_POCKET ~~ []
  SAY SELECT_RARE1 @849
  SAY SELECT_RARE2 @850
  WRITE_SHORT 0x246 (IDS_OF_SYMBOL (~kit~ ~X3Bard~)) 
 // Character ToB 
COPY ~%MOD_FOLDER%/Cre/X3Reb25.cre~ ~override/X3Reb25.cre~
  SAY NAME1 @790
  SAY NAME2 @790
  WRITE_ASCII 0x248 ~X3Reb25~ #8  //override script
  WRITE_ASCII 0x280 ~X3Reb~ #32  //DV
  WRITE_ASCII 0x2cc ~X3Reb25~ #8   //pre-joining dialogue file
  WRITE_ASCII 0X34 ~X3RebM~ #8   
  WRITE_ASCII 0x3c ~X3RebL~ #8  
  SAY BIO @808
  SAY INITIAL_MEETING @809
  SAY MORALE @810 
  SAY HAPPY  @811
  SAY UNHAPPY_ANNOYED @812
  SAY UNHAPPY_SERIOUS @813
  SAY UNHAPPY_BREAKING_POINT ~~ [] 
  SAY LEADER @815
  SAY TIRED @816
  SAY BORED @817
  SAY BATTLE_CRY1 @818
  SAY BATTLE_CRY2 @819
  SAY BATTLE_CRY3 @820
  SAY BATTLE_CRY4 @821
  SAY BATTLE_CRY5 @822
  SAY DAMAGE ~~ [X3RDam]
  SAY DYING ~~ [X3RDead]
  SAY HURT @825
  SAY AREA_FOREST @826
  SAY AREA_CITY @827
  SAY AREA_DUNGEON @828
  SAY AREA_DAY @829
  SAY AREA_NIGHT @830
  SAY SELECT_COMMON1 @831
  SAY SELECT_COMMON2 @834
  SAY SELECT_COMMON3 @833
  SAY SELECT_COMMON4 @851
  SAY SELECT_COMMON5 @835
  SAY SELECT_COMMON6 @836
  SAY SELECT_ACTION1 @837
  SAY SELECT_ACTION2 @838
  SAY SELECT_ACTION3 @839
  SAY SELECT_ACTION4 @840
  SAY SELECT_ACTION5 @841
  SAY SELECT_ACTION6 @842
  SAY SELECT_ACTION7 @832
  SAY SELECT_ACTION7 @843
  SAY CRITICAL_HIT @844
  SAY CRITICAL_MISS @845
  SAY TARGET_IMMUNE @846
  SAY INVENTORY_FULL @847
  SAY SPELL_DISRUPTED @848
  SAY SET_A_TRAP ~~ []
  SAY HIDDEN_IN_SHADOWS ~~ []
  SAY PICKED_POCKET ~~ []
  SAY SELECT_RARE1 @849
  SAY SELECT_RARE2 @850
  WRITE_SHORT 0x246 (IDS_OF_SYMBOL (~kit~ ~X3Bard~)) 
  
    APPEND ~pdialog.2da~
~X3Reb       X3RebP             X3RebJ			X3RebD~
UNLESS ~X3Reb ~
UNLESS ~25POST~

APPEND ~pdialog.2da~
~X3Reb        X3RebP             X3RebJ            X3RebD             X3Reb25P             X3Reb25J		X3Reb25D		X3Reb25~
UNLESS ~X3Reb~
IF ~25POST~

APPEND ~interdia.2da~
~X3Reb       BX3Reb~
UNLESS ~X3Reb~
UNLESS ~25FILE~

APPEND ~interdia.2da~
~X3Reb       BX3Reb       BX3Reb25~
UNLESS ~X3Reb~
IF ~25FILE~

//Epilogues
COPY ~%MOD_FOLDER%/Epilogue/X3RebEp.2da~ ~override/X3Reb01.2da~
REPLACE ~99999~ @51

COPY ~%MOD_FOLDER%/Epilogue/X3RebEp.2da~ ~override/X3Reb02.2da~
REPLACE ~99999~ @52

COPY ~%MOD_FOLDER%/Epilogue/X3RebEp.2da~ ~override/X3Reb3M.2da~
REPLACE ~99999~ @53

COPY ~%MOD_FOLDER%/Epilogue/X3RebEp.2da~ ~override/X3Reb4M.2da~
REPLACE ~99999~ @54

COPY ~%MOD_FOLDER%/Epilogue/X3RebEp.2da~ ~override/X3Reb3F.2da~
REPLACE ~99999~ @55

COPY ~%MOD_FOLDER%/Epilogue/X3RebEp.2da~ ~override/X3Reb4F.2da~
REPLACE ~99999~ @56

COPY ~%MOD_FOLDER%/Epilogue/X3RebEp.2da~ ~override/X3Reb05.2da~
REPLACE ~99999~ @57

// Journal Entries 
ADD_JOURNAL TITLE (@40003) @40004 @40005 @40006 @40007 USING ~%MOD_FOLDER%/Tra/english/Recorder_bg2.tra~ // The Remover Quest
ADD_JOURNAL TITLE (@40008) @40009 @40010 @40011 @40012 @40013 @40014 USING ~%MOD_FOLDER%/Tra/english/Recorder_bg2.tra~ // Phelgrim



  // Portraits 

		COPY ~%MOD_FOLDER%/Portraits/X3RebL.bmp~ ~override/X3RebL.bmp~
		COPY ~%MOD_FOLDER%/Portraits/X3RebM.bmp~ ~override/X3RebM.bmp~
// Creatures 
COPY ~%MOD_FOLDER%/Cre/X3RMOM.cre~ ~override/X3RMOM.cre~
  WRITE_ASCII 0x248 ~X3RMOM~ #8  //override script
  WRITE_ASCII 0x280 ~X3RMOM~ #32  //DV
  WRITE_ASCII 0x2cc ~X3RMOM~ #8   // Dialogue 
  SAY NAME1 @852
  SAY NAME2 @852
// Creatures 
COPY ~%MOD_FOLDER%/Cre/X3RFER.cre~ ~override/X3RFER.cre~
  WRITE_ASCII 0x248 ~X3RFER~ #8  //override script
  WRITE_ASCII 0x280 ~X3RFER~ #32  //DV
  WRITE_ASCII 0x2cc ~X3RFER~ #8   // Dialogue 
  SAY NAME1 @791
  SAY NAME2 @791  
COPY ~%MOD_FOLDER%/Cre/X3RAMB1.cre~ ~override/X3RAMB1.cre~
  WRITE_ASCII 0x248 ~X3RAMB1~ #8  //override script
  WRITE_ASCII 0x280 ~X3RAMB1~ #32  //DV
  WRITE_ASCII 0x2cc ~X3RAMB1~ #8   // Dialogue 
  SAY NAME1 @853
  SAY NAME2 @853   
COPY ~%MOD_FOLDER%/Cre/X3RAMB2.cre~ ~override/X3RAMB2.cre~
  WRITE_ASCII 0x248 ~X3RAMB2~ #8  //override script
  WRITE_ASCII 0x280 ~X3RAMB2~ #32  //DV
  WRITE_ASCII 0x2cc ~X3RAMB2~ #8   // Dialogue 
  SAY NAME1 @854
  SAY NAME2 @854    
COPY ~%MOD_FOLDER%/Cre/X3REMOVE.cre~ ~override/X3REMOVE.cre~
  WRITE_ASCII 0x248 ~X3REMOVE~ #8  //override script
  WRITE_ASCII 0x280 ~X3REMOVE~ #32  //DV
  WRITE_ASCII 0x2cc ~X3REMOVE~ #8   // Dialogue 
  SAY NAME1 @855
  SAY NAME2 @855  
COPY ~%MOD_FOLDER%/Cre/X3RTANYA.cre~ ~override/X3RTANYA.cre~
  WRITE_ASCII 0x248 ~X3RTANYA~ #8  //override script
  WRITE_ASCII 0x280 ~X3RTANYA~ #32  //DV
  WRITE_ASCII 0x2cc ~X3RTANYA~ #8   // Dialogue 
  SAY NAME1 @856
  SAY NAME2 @856  
COPY ~%MOD_FOLDER%/Cre/X3RKID.cre~ ~override/X3RKID.cre~
  WRITE_ASCII 0x248 ~X3RKID~ #8  //override script
  WRITE_ASCII 0x280 ~X3RKID~ #32  //DV
  WRITE_ASCII 0x2cc ~X3RKID~ #8   // Dialogue 
  SAY NAME1 @857
  SAY NAME2 @857 
COPY ~%MOD_FOLDER%/Cre/X3RKID.cre~ ~override/X3Rlove.cre~
  WRITE_ASCII 0x248 ~X3Rlove~ #8  //override script
  WRITE_ASCII 0x280 ~X3Rlove~ #32  //DV
  WRITE_ASCII 0x2cc ~X3Rlove~ #8   // Dialogue 
  SAY NAME1 @857
  SAY NAME2 @857  
COPY ~%MOD_FOLDER%/Cre/X3RPIR1.cre~ ~override/X3RPIR1.cre~
  WRITE_ASCII 0x248 ~X3RPIR1~ #8  //override script
  WRITE_ASCII 0x280 ~X3RPIR1~ #32  //DV
  WRITE_ASCII 0x2cc ~X3RPIR1~ #8   // Dialogue 
  SAY NAME1 @858
  SAY NAME2 @858   
COPY ~%MOD_FOLDER%/Cre/X3RPIR2.cre~ ~override/X3RPIR2.cre~
  WRITE_ASCII 0x248 ~X3RPIR2~ #8  //override script
  WRITE_ASCII 0x280 ~X3RPIR2~ #32  //DV
  WRITE_ASCII 0x2cc ~X3RPIR2~ #8   // Dialogue 
  SAY NAME1 @858
  SAY NAME2 @858    
COPY ~%MOD_FOLDER%/Cre/X3RPIR3.cre~ ~override/X3RPIR3.cre~
  WRITE_ASCII 0x248 ~X3RPIR3~ #8  //override script
  WRITE_ASCII 0x280 ~X3RPIR3~ #32  //DV
  WRITE_ASCII 0x2cc ~X3RPIR3~ #8   // Dialogue 
  SAY NAME1 @858
  SAY NAME2 @858    
COPY ~%MOD_FOLDER%/Cre/X3RPIR4.cre~ ~override/X3RPIR4.cre~
  WRITE_ASCII 0x248 ~X3RPIR4~ #8  //override script
  WRITE_ASCII 0x280 ~X3RPIR4~ #32  //DV
  WRITE_ASCII 0x2cc ~X3RPIR4~ #8   // Dialogue 
  SAY NAME1 @858
  SAY NAME2 @858   
COPY ~%MOD_FOLDER%/Cre/X3RM.cre~ ~override/X3RM.cre~
  WRITE_ASCII 0x248 ~X3RM~ #8  //override script
  WRITE_ASCII 0x280 ~X3RM~ #32  //DV
  WRITE_ASCII 0x2cc ~X3RM~ #8   // Dialogue 
  SAY NAME1 @859
  SAY NAME2 @859  
COPY ~%MOD_FOLDER%/Cre/X3RM25.cre~ ~override/X3RM25.cre~
  WRITE_ASCII 0x248 ~X3RM25~ #8  //override script
  WRITE_ASCII 0x280 ~X3RM25~ #32  //DV
  WRITE_ASCII 0x2cc ~X3RM25~ #8   // Dialogue 
  SAY NAME1 @859
  SAY NAME2 @859    
COPY ~%MOD_FOLDER%/Cre/X3RPHEL.cre~ ~override/X3RPHEL.cre~
  WRITE_ASCII 0x248 ~X3RPHEL~ #8  //override script
  WRITE_ASCII 0x280 ~X3RPHEL~ #32  //DV
  WRITE_ASCII 0x2cc ~X3RPHEL~ #8   // Dialogue 
  SAY NAME1 @860
  SAY NAME2 @860   
COPY ~%MOD_FOLDER%/Cre/X3RB1.cre~ ~override/X3RB1.cre~
  WRITE_ASCII 0x248 ~X3RB1~ #8  //override script
  WRITE_ASCII 0x280 ~X3RB1~ #32  //DV
  WRITE_ASCII 0x2cc ~X3RB1~ #8   // Dialogue 
  SAY NAME1 @861
  SAY NAME2 @861 
COPY ~%MOD_FOLDER%/Cre/X3RB2.cre~ ~override/X3RB2.cre~
  WRITE_ASCII 0x248 ~X3RB2~ #8  //override script
  WRITE_ASCII 0x280 ~X3RB2~ #32  //DV
  WRITE_ASCII 0x2cc ~X3RB~ #8   // Dialogue 
  SAY NAME1 @861
  SAY NAME2 @861    
COPY ~%MOD_FOLDER%/Cre/X3RB3.cre~ ~override/X3RB3.cre~
  WRITE_ASCII 0x248 ~X3RB3~ #8  //override script
  WRITE_ASCII 0x280 ~X3RB3~ #32  //DV
  WRITE_ASCII 0x2cc ~X3RB~ #8   // Dialogue 
  SAY NAME1 @861
  SAY NAME2 @861  
COPY ~%MOD_FOLDER%/Cre/X3RB4.cre~ ~override/X3RB4.cre~
  WRITE_ASCII 0x248 ~X3RB4~ #8  //override script
  WRITE_ASCII 0x280 ~X3RB4~ #32  //DV
  WRITE_ASCII 0x2cc ~X3RB~ #8   // Dialogue 
  SAY NAME1 @861
  SAY NAME2 @861   
COPY ~%MOD_FOLDER%/Cre/X3RB5.cre~ ~override/X3RB5.cre~
  WRITE_ASCII 0x248 ~X3RB5~ #8  //override script
  WRITE_ASCII 0x280 ~X3RB5~ #32  //DV
  WRITE_ASCII 0x2cc ~X3RB~ #8   // Dialogue 
  SAY NAME1 @861
  SAY NAME2 @861   
COPY ~%MOD_FOLDER%/Cre/X3RB6.cre~ ~override/X3RB6.cre~
  WRITE_ASCII 0x248 ~X3RB6~ #8  //override script
  WRITE_ASCII 0x280 ~X3RB6~ #32  //DV
  WRITE_ASCII 0x2cc ~X3RB~ #8   // Dialogue 
  SAY NAME1 @861
  SAY NAME2 @861   
// Creature and Cutscene Scripts 
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Scripts/X3RMOM.baf~ 
~%MOD_FOLDER%/Scripts/X3Reb.baf~ 
~%MOD_FOLDER%/Scripts/X3RebD.baf~
~%MOD_FOLDER%/Scripts/X3RReset.baf~
~%MOD_FOLDER%/Scripts/X3Reb25.baf~ 
~%MOD_FOLDER%/Scripts/X3Reb25D.baf~ 
~%MOD_FOLDER%/Scripts/X3RCut01.baf~ 
~%MOD_FOLDER%/Scripts/X3RCut02.baf~
~%MOD_FOLDER%/Scripts/X3RCut03.baf~//Cutscene for Helga Spell 
~%MOD_FOLDER%/Scripts/X3Rbodhi.baf~
~%MOD_FOLDER%/Scripts/X3RPIR1.baf~
~%MOD_FOLDER%/Scripts/X3RPIR4.baf~
~%MOD_FOLDER%/Scripts/X3RPHEL.baf~
~%MOD_FOLDER%/Scripts/X3RM.baf~ 
~%MOD_FOLDER%/Scripts/X3RB1.baf~ 
~%MOD_FOLDER%/Scripts/X3RW1.baf~ 
~%MOD_FOLDER%/Scripts/X3RM25.baf~ 

// Area Scripts 
	EXTEND_TOP ~ar0046.bcs~ ~%MOD_FOLDER%/Scripts/ar0046.baf~
	EXTEND_TOP ~ar0041.bcs~ ~%MOD_FOLDER%/Scripts/ar0041.baf~	
  EXTEND_TOP ~ar0319.bcs~ ~%MOD_FOLDER%/Scripts/ar0319.baf~
    EXTEND_BOTTOM ~ar0314.bcs~ ~%MOD_FOLDER%/Scripts/ar0314.baf~
    EXTEND_BOTTOM ~ar1600.bcs~ ~%MOD_FOLDER%/Scripts/ar1600.baf~
	EXTEND_BOTTOM ~ar1700.bcs~ ~%MOD_FOLDER%/Scripts/ar1700.baf~
	EXTEND_BOTTOM ~ar1800.bcs~ ~%MOD_FOLDER%/Scripts/ar1800.baf~
    EXTEND_BOTTOM ~ar1601.bcs~ ~%MOD_FOLDER%/Scripts/ar1601.baf~
	    EXTEND_BOTTOM ~ar5003.bcs~ ~%MOD_FOLDER%/Scripts/ar5003.baf~
  //Dialogue 
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3RFER.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3RFER.tra~ 
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3RMOM.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3RMOM.tra~ 
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3RAMB.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3RAMB.tra~	
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3Reb.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3Reb.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3Reb25.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3Reb25.tra~ 
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3Remove.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3Remove.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3RPHEL.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3RPHEL.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3RPIR1.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3RPIR1.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3RM25.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3RM25.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3RB1.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3RB1.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/BX3Reb.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/BX3Reb.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3RebJ.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3RebJ.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/BX3Reb25.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/BX3Reb25.tra~
COMPILE	EVALUATE_BUFFER ~%MOD_FOLDER%/Dialogue/X3Reb25J.d~ USING ~%MOD_FOLDER%/tra/%LANGUAGE%/X3Reb25J.tra~

LOAD_TRA ~%MOD_FOLDER%/Tra/%LANGUAGE%/setup.tra~