IF
Global("X3KGarrisionSpawns","AR0332",0)
Global("X3KalQuest","GLOBAL",3)
THEN RESPONSE #100
CreateCreature("X3KJIL",[469.287],SW)
CreateCreature("X3KBRYCE",[404.466],SW)
SetGlobal("X3KGarrisionSpawns","AR0332",1)
Continue()
END 

IF 
Dead("X3KBRYCE")
Global("X3KalClearBryce","AR0332",0)
THEN RESPONSE #100 
ActionOverride("X3KBryce",DestroySelf())
SetGlobal("X3KalClearBryce","AR0332",1)
END
