IF 
InParty("X3Hel")
See("X3Hel")
Global("X3HMomTalk","LOCALS",0)
THEN RESPONSE #100 
SetGlobal("X3HMomTalk","LOCALS",1)
Dialogue("X3Hel")
END 

  IF
    AttackedBy([GOODCUTOFF],DEFAULT)
    Allegiance(Myself,NEUTRAL)
	InParty("X3Hel")
  THEN
    RESPONSE #100
      Enemy()
	  ActionOverride("X3Hel",ChangeAIScript("",DEFAULT))
	  ActionOverride("X3Hel",ChangeAIScript("",GENERAL))
	  ActionOverride("X3Hel",LeaveParty())
	  ActionOverride("X3Hel",Enemy())
 END 
