IF
	RealGlobalTimerExpired("X3RebToBLoveTimer","GLOBAL")
	Global("X3RebRomanceActive","GLOBAL",2) 
    IsValidForPartyDialogue(Myself)
	IsValidForPartyDialogue(Player1)
	Global("X3RebLoveTalk","LOCALS",5)	
	Global("X3RebWraithTalk","LOCALS",2)
THEN RESPONSE #100 
	PlaySong(0)
	RealSetGlobalTimer("X3RebToBTalkTimer","GLOBAL",3200)
	IncrementGlobal("X3RebLoveTalk","LOCALS",1)
	StartDialogueNoSet(Player1)
END 